.github/PULL_REQUEST_TEMPLATE.md

> Resolves: #25 
Used keywords next to the issue id to link the pr to an issue.
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
PR does not link to an issue, so the issue still remains even after the PR is merged/closed.
Issue will be automatically linked to the PR.

chore(github): Update the PR template with issue linking keywords

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation_proposal.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/regression_report.md

Added default project to the issue templates so the issue is automatically added to the [One Platform Development Board](https://github.com/orgs/1-Platform/projects/1).
And removed some checklists from the templates.
No

chore(github): Update Issue Templates with default project

---

packages/home-spa/src/js/controller.js
packages/home-spa/src/mocks/stub.js

fix(#254) - Added feedback to stub
Added the following object to the microserviceDetailsMock
```
{
title: 'Feedback',
info: `One platform's server-side Feedback GraphQL microservice. This microservice will allow users to talk to the feedback database and can perform operations like addFeedback, updateFeedback, deleteFeedback & listFeedback`,
features: [
'Provide feedback for the Platform or the hosted apps from anywhere',
'Allow users to share user experience feedback and feature requests',
'JIRA integration to automatically create JIRAs for every feedback',
],
illustration: 'img/Notification-illustration.svg',
}
```
No

fix(#254) -  Add feedback microservice information to the microservice details page

---

docker-compose.yml
packages/ssi-service/Dockerfile
packages/ssi-service/package-lock.json
packages/ssi-service/package.json
packages/ssi-service/public/index.html
packages/ssi-service/src/default.html
packages/ssi-service/webpack.config.js

The SSI template assets are not moved to SPAship via the SPAship sync, so to tackle that, and make is future proof, I've added an environment variable for the asset paths (`SSI_HOSTNAME`).
This will allow us to host the static files required for the SSI templates elsewhere without having to worry about moving them to the SPAship server.
No.
N/A
- [-] Was this feature demo'd and the design review approved?

fix(ssi-paths): Added env variable for ssi assets path

---

packages/home-service/src/helpers.ts
packages/home-service/src/schema.ts
packages/home-service/src/typedef.graphql
packages/home-service/src/types.d.ts

fix(#360) - Added permissions array to the schema, type.d.ts and type def.graphql
Added permissions array to the schema 
No

fix(#360) - Additional field for permissions in the Home Service Schema

---

packages/home-service/src/resolver.ts
packages/home-service/src/typedef.graphql

Added getHomeTypeByUser API endpoint in graphql and resolver using mongo
No

feat(#419) - Create getHomeTypeByUser API endpoint in home-service

---

packages/feedback-service/src/typedef.graphql
packages/home-service/src/helpers.ts
packages/home-service/src/typedef.graphql
packages/home-service/src/types.d.ts
packages/notifications-service/src/helpers.ts
packages/notifications-service/src/notificationConfig/resolver.ts
packages/notifications-service/src/notificationConfig/typedef.graphql
packages/notifications-service/src/typedef.graphql
packages/notifications-service/src/types.d.ts
packages/user-service/src/typedef.graphql

Renamed the duplicate graphql types for UserType and
HomeType defined in Notifications, Home and Feedback Microservices.
Yes
N/A

fix(graphql-schema): Changed duplicate GraphQL types for User and Home

---

packages/notifications-service/src/__tests__/notificationConfig.spec.ts
packages/notifications-service/src/notificationConfig/resolver.ts
packages/notifications-service/src/notificationConfig/typedef.graphql

Changed the graphql query parameter name in Notifications Microservice
No
N/A

hotfix(notification-service): typo in notifications endpoint

---

.github/workflows/notify.yml

Using pull_request_target instead of pull_request to fix forked repo actions

fix: Using pull_request_target instead of pull_request to fix forked repo actions

---

packages/home-spa/src/styles/main.scss

Added background as center top and view height as 90
No

fix(#619) - Home-SPA illustration height breaking for smaller screens

---

renovate.json

Updated Renovate configuration to group all minors & patches together.

chore(renovate): Group minors & patches together

---

packages/ssi-service/src/nav/nav.css

- Added some default CSS styles and fallbacks for the Menu Drawer and the search bar to extend support to browsers like Safari.
- Elevated the "Notifications" heading to make it float on top of the notifications in the notification drawer.
No.
N/A

fix(ssi): CSS fallbacks for Safari and unsupported broswers

---

packages/ssi-service/src/nav/nav.css
packages/ssi-service/src/nav/nav.js

- Some small CSS changes
- Changes the user profile url from user-profile-spa to user-group-spa. (i.e. `/user-groups/user/<cn>`)
No
N/A

chore(ssi): Minor css changes for SSI and User profile url fix

---

packages/user-group-spa/src/App.jsx
packages/user-group-spa/src/components/Home.jsx

The `useState` hook loops infinitely in some cases when the react app is deployed. So added a dependency to the `useState` to make sure it only runs once.
No.
N/A

fix(user-groups-spa): Fixed useState looping in some edge cases

---

packages/ssi-service/src/auth.js

Replace the `history.pushState` to `history.replaceState` for the post-auth redirect.
It helps keep the browser history clean, and avoids navigation issues when navigating back to an old page, by skipping the intermediate auth callback url.
No.
N/A

hotfix(ssi): Changed post-auth redirect to use replaceState

---

packages/documentation-spa/docs/faqs.md

Found a broken link for research repository FAQs
No

Fix: broken link for Research repo FAQs

---

packages/home-spa/src/styles/main.scss

Remove right and added a margin-left which fixed it for both firefox and chrome
No

fix(#732) - Citation (quotes) position needs to be fixed on the home page for firefox

---

packages/ssi-service/src/auth.js
packages/ssi-service/src/default.html

- Changed the keycloak auth flow to standard, from implicit, which allows the use of refresh tokens to update the access tokens.
- And added automatic updateToken logic
No.
N/A

enhancement(sso): Changed the SSO auth flow to standard flow

---

packages/ssi-service/package-lock.json
packages/ssi-service/package.json
packages/ssi-service/public/index.html
packages/ssi-service/src/auth.js
packages/ssi-service/src/default.html
packages/ssi-service/src/feedback-panel/feedback.js
packages/ssi-service/src/nav/nav.css
packages/ssi-service/src/nav/nav.js
packages/ssi-service/webpack.config.js

Style load issues in the SSI nav and feedback-panel components
The to-string-loader caused some problems and was returning a `[object Module]` instead of the actual css contents.\
So removed it in favour of `.toString()`
Also, updated the default.html so the loader is added and removed from the DOM much more cleanly.
No.
N/A

fix(ssi): SSI cleanup and style-loader fix

---

packages/home-spa/src/app.js

Fixes #786 
Footer links update from mojo to source:
"One Platform in Mojo" change the Text to 
One Platform in Source: https://source.redhat.com/groups/public/pnt-devops/oneportal
Weekly blog: https://source.redhat.com/groups/public/pnt-devops/oneportal/one_portal_blog

changes the quick links in the footer.

---

packages/ssi-service/src/default.html
packages/ssi-service/src/feedback-panel/feedback.js
packages/ssi-service/src/nav/nav.js

Adds null checks for `window.OpAuthHelper` and `window.OpNotification` to avoid null/undefined errors when using feedback-panel independently.
No.
N/A

fix(ssi): Adds NullCheck for user auth in SSI Feedback panel

---

packages/user-group-service/src/types.d.ts

Due to recent updates in the mongoose type definitions, the build broke for User Group with as error for _id type mismatch.
Making the field optional fixes it.
No
N/A

fix(user-group-service): Fixes user-group-service build error for _id type

---

packages/notifications-service/package-lock.json
packages/notifications-service/package.json

There are some breaking changes in ^5.10.9
which cause the build to fail with some lint errors
No.
N/A

fix(notifications-service): Hard locked mongoose to v5.10.8

---

.github/workflows/codeql-analysis.yml

n.a
CodeQL scanning is required only on merge commits, not on every PR. Removing the PR trigger. https://github.com/1-Platform/one-platform/pull/861/checks?check_run_id=1727515955#step:4:1 is an example of this recommendation.
No
n/a

chore: remove codeql scanning for PRs

---

packages/api-gateway-service/service.ts

Case sensitivity error for "Bearer" in authorization header.
Although there's no apparent standard for the case in the Authorization header value, title case is used generally, but wanted to make it case insensitive so it would work even for non-standard implementations.
No.

fix(api-gateway): Removes case sensitivity from authorization header

---

packages/home-spa/.htaccess
packages/home-spa/src/404.html
packages/home-spa/src/index.html
packages/home-spa/webpack.config.js

- Adds a .htaccess file to the home-spa to handle 404 errors by returning the 404.html page instead
- And also replaces relative img paths to absolute especially in 404.html page
No.
N/A

fix(404-page): Adds htaccess for 404 page (in the home-spa)

---

.github/workflows/build-api-gateway.yml
.github/workflows/build-apps-service.yml
.github/workflows/build-feedback-service.yml
.github/workflows/build-notifications-service.yml
.github/workflows/build-search-service.yml
.github/workflows/build-user-group-service.yml

Inconsistent username credentials for ghcr image deployments in the gh-actions workflow.
No. The new secret added to the workflow files is already added to the repository secrets.
N/A

fix(ghcr): Adds static actor for container build gh-actions

---

packages/home-spa/src/js/controller.js
packages/home-spa/src/styles/main.scss

Limited the number of links to 10 and also added a flex-wrap
No

fix(#928) - 404 page ui breaks on stage and prod due to > 8 apps being displayed in the same row

---

packages/documentation-spa/docs/microservices/search/search-service.md
packages/documentation-spa/sidebars.js

- Added search microservice documentation to Doc-SPA and correct-ID
No

fix(#959) - Add a search microservice guide for One Platform in doc SPA

---

packages/apps-service/src/modules/apps/resolver.ts

ONEPLAT-1108
The `updateApp` mutation returns the old data before the app was updated. Had to add a `{ new: true }` to the `findByIdAndUpdate` method.
No.
N/A

fix(apps-service): Fixes updateApp mutation to return updated details

---

packages/apps-service/src/@types/apps/index.d.ts
packages/apps-service/src/@types/microservices/index.d.ts
packages/apps-service/src/index.ts
packages/apps-service/src/modules/apps/model.ts
packages/apps-service/src/modules/apps/resolver.ts
packages/apps-service/src/modules/apps/schema.gql.ts
packages/apps-service/src/modules/microservices/index.ts
packages/apps-service/src/modules/microservices/model.ts
packages/apps-service/src/modules/microservices/resolver.ts
packages/apps-service/src/modules/microservices/schema.gql.ts
packages/apps-service/src/utils/unique-id-from-path.ts

The `myApps` query returned an empty array due to a misconfigured schema.
- Fixes myApps query and adds resolvers for service
- Refactored Apps resolvers to include `appId`, and cleanup the permissions field
- Adds queries and mutations for Services
No.
N/A

fix(apps-service): Fixes myApps query and adds resolvers for service

---

packages/ssi-service/.env.example
packages/ssi-service/src/feedback-panel/api.js
packages/ssi-service/src/nav/api.js

- `getHomeType` query has been deprecated in favour of new apps service
- also added a separate environment variable for subscriptions url
No.
N/A

fix(ssi): Replaced the deprecated getHomeType query with the new apps query

---

packages/apps-service/src/modules/apps/model.ts
packages/apps-service/src/modules/apps/resolver.ts
packages/apps-service/src/modules/apps/schema.gql.ts

- Additional fields to the app model for future use cases for database and lighthouse configs.
- The appId for apps without any path or where the path is `/` was being generated as an empty string. Now the app name will be used as a fallback
No.
N/A

feat(apps-service): Additional fields to the app service, and a fix for the appId

---

packages/ssi-service/src/nav/nav.js

Minor variable name change
The field for app.active was changed to `isActive` in the new app service.
No.
N/A

fix(ssi-nav): Incorrect variable name in app drawer in SSI

---

packages/user-group-service/src/groups/resolver.ts
packages/user-group-service/src/groups/typedef.graphql

Supplements ONEPLAT-1141
Fetching members details from cache as group API does not provide all the fields
Yes
<details>
</details>

Feat(#1141): Fetching members details from cache as group API does not provide all the fields

---

e2e/helper/apps.list.js
packages/documentation-spa/blog/2020-08-18-announcing-one-platform-beta.md
packages/documentation-spa/docs/apps/assets.md
packages/documentation-spa/docs/apps/hosted/mod-handovers/mod-handover-spa.md
packages/documentation-spa/docs/apps/hosted/research-repository/research-repository-spa.md
packages/documentation-spa/docs/apps/internal/feedback/feedback-spa.md
packages/documentation-spa/docs/apps/internal/home/home-spa.md
packages/documentation-spa/docs/apps/internal/notifications/notifications-spa.md
packages/documentation-spa/docs/apps/internal/ssi-service/ssi-service.md
packages/documentation-spa/docs/apps/internal/user-groups/user-groups-spa.md
packages/documentation-spa/docs/cli/op-cli.md
packages/documentation-spa/docs/components/component-library.md
packages/documentation-spa/docs/documentation/styleguide.md
packages/documentation-spa/docs/faqs.md
packages/documentation-spa/docs/getting-started/get-started.md
packages/documentation-spa/docs/microservices/apps-service/app-service.md
packages/documentation-spa/docs/microservices/authorization/authorization-service.md
packages/documentation-spa/docs/microservices/feedback/feedback-service.md
packages/documentation-spa/docs/microservices/home/home-service.md
packages/documentation-spa/docs/microservices/notifications/get-started.md
packages/documentation-spa/docs/microservices/notifications/notifications-service.md
packages/documentation-spa/docs/microservices/search/search-service.md
packages/documentation-spa/docs/microservices/user-groups/user-groups-service.md
packages/documentation-spa/package-lock.json
packages/documentation-spa/package.json
packages/documentation-spa/sidebars.js
packages/home-spa/src/res/static/microservices.json
packages/user-group-spa/src/App.jsx

Yes. Some of the permalink to the documentation from other SPAs might be broken. I've tried to fix it wherever I could find the old links in home spa and user-group spa.
Need to check if any other SPA requires these changes.
<details>
| Label | Screenshot |
|---|---|
| Sidebar reordered | <img width="301" alt="Screenshot 2021-07-07 at 6 51 30 PM" src="https://user-images.githubusercontent.com/19623278/124766306-6df5bc00-df54-11eb-9e96-0c2d72a42d9a.png"> |
| Deprecation notice on Home Service | <img width="1364" alt="Screenshot 2021-07-07 at 6 50 37 PM" src="https://user-images.githubusercontent.com/19623278/124766450-9087d500-df54-11eb-96b8-7a2cd1b5405f.png"> |
| Apps Service Documentation | <img width="974" alt="Screenshot 2021-07-07 at 6 53 34 PM" …

(docs/apps): Adds documentation for App Service and some permalink changes for other docs

---

packages/documentation-spa/docs/apps/internal/feedback/feedback-spa.md
packages/documentation-spa/docs/faqs.md
packages/documentation-spa/docs/microservices/api-gateway/api-gateway.md

Broken links in the documentation spa in pages:
- FAQs
- API Gateway
- Feedback SPA
No.
Error message during build:

Fixes broken links in documentation spa

---

packages/apps-service/src/modules/apps/model.ts
packages/apps-service/src/modules/apps/resolver.ts
packages/apps-service/src/modules/apps/schema.gql.ts
packages/apps-service/src/modules/microservices/resolver.ts
packages/apps-service/src/modules/microservices/schema.gql.ts

- Added support to query by `id` in the `findApps`, `app`, `findService` and `service` queries
No.
N/A

feat(apps-service): Adds support for id in findApps and app query

---

packages/developer-console-spa/src/App.tsx
packages/developer-console-spa/src/components/AddAppForm.tsx
packages/developer-console-spa/src/components/AppIndex.tsx
packages/developer-console-spa/src/components/AppOverview.tsx
packages/developer-console-spa/src/components/AppSettings.tsx
packages/developer-console-spa/src/components/Sidebar.tsx
packages/developer-console-spa/src/context/AppContext.tsx
packages/developer-console-spa/src/hooks/useAppAPI.ts
packages/developer-console-spa/src/react-app-env.d.ts
packages/developer-console-spa/src/services/app.ts
packages/developer-console-spa/src/utils/gql-queries/delete-app.ts
packages/developer-console-spa/src/utils/gql-queries/index.ts
packages/developer-console-spa/src/utils/gql-queries/update-app.ts

ONEPLAT-1057
- Implemented an App Settings page where users can modify the app information
- With editable form for modifying the basic details of the app, along with the ability to archive, disable and delete the app entirely.
No.
<details>
- App Settings Page
</details>

feat(dev-console): Adds AppSettings page to modify apps

---

packages/apps-service/src/modules/apps/resolver.ts
packages/apps-service/src/modules/microservices/resolver.ts

The `app` and `findApps` queries broke functionality for null value of `id` field.
Handled the null value by adding extra checks.
No.
N/A

fix(apps-service): Handled null value for id in apps service

---

packages/lighthouse-service/Dockerfile

Installation of lhci fails on image with the NPM_CONFIG_PREFIX param which led to workflow failure while testing docker. For now i am rolling back the change. 
No
N/A

(hotfix:lh-image) - Rolling back the changes on github image because dependency installation scope is different

---

packages/api-gateway-service/.env.example
packages/api-gateway-service/service.ts
packages/api-gateway-service/src/remote-schema.ts

Adds an environment variable for easy configuration of the Base path of the GraphQL API Gateway and its subscriptions URL.
No.
N/A

chore(api-gateway): Adds configurability for API Gateway Base URL

---

packages/developer-console-spa/src/components/Sidebar.css

Added `position: sticky` and `overflow-y` to the sidebar and the menu_list to the sidebar on the developer console to accomodate overflowing content inside the sidebar, as well as outside.
N/A
<details>
</details>

fix(dev-console): Fixes scroll overflow in dev console sidebar

---

renovate.json

Fixes the incorrect syntax for renovate schedule in the config.
Created from github.dev

fix(renovate): Fixes the renovate config schedule

---

packages/reverse-proxy-service/src/couchdb/resolver.ts

Added a `user:` prefix to the uid roles in the couchdb middleware in reverse-proxy.
This allows the devs to identify between a uid and a group in the userCtx roles for better authorization in couchdb.
Yes.
Any existing apps that rely on the userCtx roles for authorization will have to change the way they check the user roles for auth.
N/A

Adds user prefix in the userCtx role for couchdb

---

packages/reverse-proxy-service/package-lock.json
packages/reverse-proxy-service/package.json
packages/reverse-proxy-service/src/app.ts
packages/reverse-proxy-service/src/config/env.ts
packages/reverse-proxy-service/src/index.ts
packages/reverse-proxy-service/src/middleware/jwtAuth.ts
packages/reverse-proxy-service/src/utils/logger.ts

Incomplete logging in the reverse-proxy
winston provides better logging with logging levels, and flexibility to easily add additional transports for when we want to offload the logs to other places, like logstash or logfiles.
No.
<details>
</details>

chore(reverse-proxy-service): Added winston for better logging in reverse-proxy

---

docker-compose.yml

Added the couchdb as a service to the main `docker-compose.yml`.
It is a dependency of the reverse-proxy-service and the apps-service.
No.
N/A

chore(docker-compose): Added couchdb service to the main docker-compose

---

packages/opc-base/package-lock.json
packages/opc-base/package.json
packages/opc-base/src/config/graphql.ts
packages/opc-base/src/opc-provider/opc-provider.ts

1. Fixed notification subscription missing target variable
2. Fixed chrome server error
The issue was, the header `content-type: application/json`. From previous code for apollo it was explicitly given in which URQL cases it's not needed. In firefox header was passed as it is. But in chrome when the header was given it appends to that header  causing `content-type: application/json, application/json` failing the server operation.
FIx was just removing that explicit header and letting urql handle it by itself.
No
<details>
</details>

fix: opc-base chrome error and subscription variable fix

---

packages/lighthouse-spa/package-lock.json
packages/lighthouse-spa/package.json
packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
packages/lighthouse-spa/src/app/playground/components/home/home.component.html
packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.spec.ts
packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.ts
packages/lighthouse-spa/src/app/shared/shared.module.ts

1602
1. Implemented stricter url validation for report generation
2. Update opc-base to latest version
No
<details>
</details>

fix(1602): implemented stricter url validation in report generation page

---

packages/opc-base/docs/opc-base.md
packages/opc-base/package-lock.json
packages/opc-base/package.json
packages/opc-base/src/opc-base/opc-base.ts
packages/opc-base/src/opc-base/types.ts

opc-base provides a singleton api that contains api for feedback, toast etc.
To avoid mutating these instances after set by opc-provider, opc-base was throwing error. This had two negative effect. 
1. React hot reloading sometimes reloads opc-provider and issue is opc-base config is singleton, so it wont be reloaded together and it contains the configuration already firing this error.
2. Doc spa reloads the provider completely on page traversal causing this error
Changing from error to warning and added debug mode to avoid apps from showing it in console if not needed.
No
<details>
</details>

feat: opc-base changed to warning on mutating config values

---

packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts
packages/lighthouse-spa/src/app/leaderboard/leaderboard.service.ts
packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.ts
packages/lighthouse-spa/src/app/playground/components/home/home.component.ts

1691
1. Changed leaderboard graphql policy to `network-policy` due to an apollo graphql collision issue with other one
2. added unsubcription to all rxjs subscription made in all pages
No
<details>
https://user-images.githubusercontent.com/31166322/143402718-7ac53b01-0d51-4a31-b4ca-61a507179f2b.mov
</details>

fix(1691): lighthouse - fixed leaderboard cache policy issue

---

packages/api-catalog-spa/package-lock.json
packages/api-catalog-spa/package.json
packages/component-catalog-spa/package-lock.json
packages/developer-console-spa/package-lock.json

1. On upgrade to react-scripts v5 builds got failed due to package-lock issue, generated new ones
2. API catalog downgraded react-script due to polyfill issue in cra webpack 5
No
<details>
</details>

hotfix: react-script package-lock file build issue

---

packages/developer-console-spa/package-lock.json
packages/developer-console-spa/package.json
packages/developer-console-spa/src/@types/Feedback/types.d.ts
packages/developer-console-spa/src/App.tsx
packages/developer-console-spa/src/components/feedback/ConfigureFeedback.tsx
packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
packages/developer-console-spa/src/hooks/useDebounce.tsx
packages/developer-console-spa/src/hooks/usePagination.tsx
packages/developer-console-spa/src/hooks/useToggle.ts
packages/developer-console-spa/src/services/feedback.ts
packages/developer-console-spa/src/utils/gql-queries/get-app-feedbacks.ts
packages/developer-console-spa/src/utils/gql-queries/index.ts

1. 1307
1. Implemented feedback list page in dev console
2. Fixed a typo made in feedback configuration in console. appId -> app.id
Yes
1. Old feedback configure page is now feedback listing page
<details>
</details>

feat(1307): dev-console - implemented feedback list page

---

packages/lighthouse-spa/package-lock.json
packages/lighthouse-spa/package.json
packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts
packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.scss
packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
packages/lighthouse-spa/src/app/utils/leaderboardTable.ts

1. Removed ASC sort order in leaderboard of dashboard page
2. Changed grid layout stacking in small screen
3. Made line chart responsive
No
<details>
</details>

hotfix(lighthouse-spa): removed asc sort order in dashboard leaderboard and made line chart responsive

---

packages/reverse-proxy-service/package-lock.json
packages/reverse-proxy-service/package.json
packages/reverse-proxy-service/src/no-cors-proxy/index.ts
packages/reverse-proxy-service/src/no-cors-proxy/resolver.ts

1. 1865
1. Fixed reverse proxy no-cors redirect to allow params and all other url parameters
Yes
1. Reverse proxy no-cors-proxy format got changed
<details>
</details>

feat(1865): reverse-proxy - fixed params missing in no-cors redirect

---

packages/lighthouse-service/package-lock.json
packages/lighthouse-service/package.json
packages/lighthouse-service/src/audit-manager/resolver.ts
packages/lighthouse-service/src/audit-manager/typedef.graphql
packages/lighthouse-service/src/e2e/lighthouse.spec.ts
packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts
packages/lighthouse-service/src/lighthouse-db-manager/types.ts

1. 1873
1. Leaderboard changed from build based stats to branch specific 
2. Updated counting operation
3. Improved accuracy in averaging
Yes.
1. `getLHRankingOfABuild` got removed and `getLHRankingOfAProjectBranch` got added
<details>
</details>

feat(1873): lighthouse-service: leaderboard updated to branch based and improved accuracy

---

packages/developer-console-spa/src/components/Sidebar.tsx

Incorrect links to overview, analytics and settings in Developer Console Sidebar
Prepended `appId` to the static links in sidebar for Overview, Analytics and Settings
No.
N/A

fix(dev-console): prepend appId to sidebar links

---

packages/lighthouse-spa/package-lock.json
packages/lighthouse-spa/package.json
packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.html

1. 1882
2. 1912
No
<details>
</details>

feat(1882,1912): lighthouse-spa - added lh server url in dashboard and leaderboard pagination

---

packages/home-spa/package-lock.json
packages/home-spa/package.json

- Removed eleventy-sass dependency
- No
<details>
</details>

chore(1499) - Replace to eleventy-plugin-sass package as it's deprecated

---

packages/lighthouse-spa/package-lock.json
packages/lighthouse-spa/package.json
packages/lighthouse-spa/src/app/shared/components/table/table.component.html
packages/lighthouse-spa/src/app/shared/components/table/table.component.scss
packages/lighthouse-spa/src/app/shared/components/table/table.component.spec.ts
packages/lighthouse-spa/src/app/shared/components/table/table.component.ts
packages/lighthouse-spa/src/app/shared/pipes/filter-list.pipe.spec.ts
packages/lighthouse-spa/src/app/shared/pipes/filter-list.pipe.ts
packages/lighthouse-spa/src/app/shared/pipes/floor.pipe.spec.ts
packages/lighthouse-spa/src/app/shared/pipes/floor.pipe.ts
packages/lighthouse-spa/src/app/shared/pipes/get-decimal.pipe.spec.ts
packages/lighthouse-spa/src/app/shared/pipes/get-decimal.pipe.ts
packages/lighthouse-spa/src/app/shared/shared.module.ts
packages/lighthouse-spa/src/app/utils/leaderboardTable.ts

1. 1985
2. 1988
1. Fixed case sensitive search in lighthouse project section
2. Added ui changes for leaderboard floating point ui
No
<details>
</details>

fix(1985): lighthouse-spa fixed case sensitive project search and improved leaderboard precision

---

packages/apps-service/.eslintignore
packages/apps-service/.eslintrc.js
packages/apps-service/.prettierrc
packages/apps-service/.test.env
packages/apps-service/jest.config.js
packages/apps-service/package-lock.json
packages/apps-service/package.json
packages/apps-service/src/__tests__/apps.spec.ts
packages/apps-service/src/__tests__/mocks/mockDatabase.ts
packages/apps-service/src/__tests__/query.gql.ts
packages/apps-service/src/app.ts
packages/apps-service/src/index.ts
packages/apps-service/src/setup/database.ts
packages/apps-service/src/setup/env.ts
packages/apps-service/tsconfig.json
packages/apps-service/tsconfig.prod.json

Tests for Apps Service
- Wrote tests for the `Apps` module in the Apps Service.
- And fixed some lint issues and cleaned up the source.
Used `mongodb-memory-server` and added some mocks to make sure the tests can run in a sandbox.
No.
<details>
</details>

tests(app-service): added tests for apps module

---

packages/reverse-proxy-service/src/restricted-spas/index.ts
packages/reverse-proxy-service/src/spec/restricted-spas.spec.ts

- Removed redundant route for a specific path, since the `*` already does the same thing
- And updated the tests
No.
N/A

chore(rproxy): remove redundant route resolvers

---

packages/api-catalog-service/package-lock.json
packages/api-catalog-service/package.json
packages/api-catalog-service/src/db/specSheet.ts

1. Fixes mongoose validation error on schemaEndpoint required
No
<details>
</details>

fix(api-catalog-service): updated mongoose validation to avoid require in schema field in db

---

packages/api-catalog-spa/package-lock.json
packages/api-catalog-spa/package.json

There was an accesibility issue of images not having alt text in api-catalog-spa. These images came from opc-feedback component being used in api-catalog-spa. this PR aims at updating the version of opc-feedback component used so that the latest version is used which has alt text for all the images being used in that component.
No
Lighthouse analytics before changes
Lighthouse analytics after changes

chore: updating the opc-feedback component version in api-catalog-spa

---

packages/home-spa/package-lock.json
packages/home-spa/src/_includes/partials/header.njk

There was an accesibility issue of images not having alt text in home-spa. These images came from opc-feedback component being used in home-spa. this PR aims at updating the version of opc-feedback component used so that the latest version is used which has alt text for all the images being used in that component.
No
Lighthouse analytics before the change 
Lighthouse analytics after the change

chore: updating the opc-feedback component version in home-spa

---

packages/home-spa/src/_includes/components/deploy.njk

There was an accessibility issue regrading the `Get started `button on the page. Two buttons with same label were pointing two different links (http://localhost:4200/console/?new=true and http://localhost:4200/console/)
No

chore: fixing multiple links for same label (accessibility issue)

---

packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html

2338 (Accessibility issues)
* Input elements without labels for the form (Screenshot attached)
* Different links for the same label (Documentation)
* There was an accessibility issue regrading the `Documentation` label in top banner and Navbar. Two buttons with same label were pointing two different links. Changed the label in Navbar to `Read Docs`
* There was an accessibility issue regrading form labels for the input elements. Updated the labels with suitable id to solve the issue
No

fix(lighthouse-spa): fixing accessibility issues in lighthouse-spa

---

package-lock.json
package.json

Specified node and npm engines in `package-lock.json`.
It is used as a constraint for the renovate bot.
Reference: https://docs.renovatebot.com/node/
No.
N/A

Enforcing npm version for renovate

---

packages/apps-service/src/modules/projects/model.ts

Duplicate key error for empty hosting array in apps service.
Added unique and sparse keys for `hosting.appId`, `hosting.name` and `hosting.url` fields.
No.
N/A

fix(apps): added sparse + unique keys for hosting

---

packages/feedback-service/src/feedbacks/resolver.ts
packages/feedback-service/src/feedbacks/typedef.graphql

Added a searchFeedbacks endpoint in the feedback service to search multiple fields of feedback schema against a query string
No

feat(feedback-service): adding searchFeedbacks endpoint in feedbacks

---

catalog-info.yml
catalog/resources/CouchDB.yml
catalog/resources/NativeMongoDB.yml
catalog/resources/NonNativeMongoDB.yml
catalog/systems/OnePlatform.yml
packages/analytics-service/catalog-info.yml
packages/api-catalog-service/catalog-info.yml
packages/api-catalog-spa/catalog-info.yml
packages/api-gateway-service/catalog-info.yml
packages/apps-service/catalog-info.yml
packages/component-catalog-spa/catalog-info.yml
packages/developer-console-spa/catalog-info.yml
packages/doc-spa/catalog-info.yml
packages/feedback-service/catalog-info.yml
packages/feedback-spa/catalog-info.yml
packages/home-spa/catalog-info.yml
packages/lighthouse-service/catalog-info.yml
packages/lighthouse-spa/catalog-info.yml
packages/opc-base/catalog-info.yml
packages/reverse-proxy-service/catalog-info.yml
packages/search-service/catalog-info.yml
packages/search-spa/catalog-info.yml
packages/user-group-service/catalog-info.yml

Included the catalog changes to the one platform repo
No
N/A

Included Backstage Catalog Items to the One Platform

---

packages/feedback-service/src/feedback-config/schema.ts
packages/feedback-service/src/feedback-config/typedef.graphql
packages/feedback-service/src/helpers.ts
packages/feedback-service/src/types.d.ts

Added a configurable field in the feedback config for a base url/url prefix for the feedback email templates.
No.
N/A

feat(feedback): add frontend url field in configs

---

packages/api-gateway-service/Dockerfile
packages/notifications-service/Dockerfile
packages/search-service/Dockerfile

Simplified the Dockerfile CMD instructions to use "node" instead of "npm", ensuring better compatibility and reducing unnecessary dependencies. This change improves the reliability and efficiency of the Docker containers for the services.
No.
N/A

fix(dockerfile): Replaced npm commands with node

---

packages/reverse-proxy-service/src/server.ts
packages/reverse-proxy-service/src/types/http.d.ts
packages/reverse-proxy-service/tsconfig.json

- Extended the `http.Agent` types to include the `maxHeaderSize` property.
- Set the global agent's `maxHeaderSize` to 16MB to allow larger request headers.
<details>
</details>

fix(reverse-proxy): increase request header size limit
