1-Platform/one-platform

CODE_OF_CONDUCT.md
Added Contributor Covenant Document highlighting the Code of Conduct for the project.
Please check if your PR fulfills the following requirements:
What kind of change does this PR introduce?
No document currently available describing the expected contributor covenant for the project.
Issue Number: #31 
Code of Conduct document would now be available for the project.
Contributor Covenant added as Code of Conduct for the project.
=> chore(#31): Add Contributors Code of Conduct

.github/PULL_REQUEST_TEMPLATE.md
The PR template does not support default values
> ### Resolves #25 
> No
- [-] Does the change have appropriate unit tests?
- [-] Did tests pass?
- [-] Was this feature demo'd and the design review approved?
=> patch(github): Edit the PR template to comment the instructions

README.md
Please check if your PR fulfils the following requirements:
What kind of change does this PR introduce?
Does not have a proper README
Issue Number: #27
=> docs(#27) - Adding readme to One Platform

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/404.html, packages/home-spa/src/index.html, packages/home-spa/webpack.dev.js, packages/home-spa/webpack.prod.js
Dependency updated html-webpack-plugin tp 4.0.0 and supporting code fix
> ### Resolves #109 
#108
To accommodate the breaking changes, home-spa minor code changes were required
The version for html-webpack-plugin is now `4.0.0`
> No (not for any other modules)
=> fix(#109): Changes required in the home-spa code as the dependencies need to be upgraded 

renovate.json
> ### Closes/Fixes/Resolves #128 
Updated renovate config to only run renovate during the weekends and use semantic versioning.
> No
=> chore(deps): Updated renovate config

packages/ldap-integration/.env.example, packages/ldap-integration/.gitignore, packages/ldap-integration/README.md, packages/ldap-integration/jest.config.js, packages/ldap-integration/package-lock.json, packages/ldap-integration/package.json, packages/ldap-integration/service.ts, packages/ldap-integration/src/api.ts, packages/ldap-integration/src/e2e/ldap.spec.ts, packages/ldap-integration/src/e2e/mock.json, packages/ldap-integration/src/helpers.ts, packages/ldap-integration/src/schema.ts, packages/ldap-integration/src/types.d.ts, packages/ldap-integration/tsconfig.json, packages/ldap-integration/tslint.json, packages/ldap-integration/webpack.common.js, packages/ldap-integration/webpack.dev.js, packages/ldap-integration/webpack.prod.js
This is the part of user/group microservice which enables the interface to talk to the ldap server this helps the 
Yes
<details>
Rest APIs are available for talking to the LDAP server which enables the microservices to communicate
</details>
=> feat(ldap-microservice): REST based ldap microservice which enables to talk to LDAP

package-lock.json
#150 
Executed `npm audit fix` to fix all vulnerabilities
No
=> fix(#150): Fixed npm audit vulnerabilities.

cli/generator-op-microservice/package-lock.json, packages/home-spa/package-lock.json, packages/ssi-service/package-lock.json, packages/user-service/package-lock.json
#150 
Executed `npm audit fix` for all packages.
No
=> fix(#150): Fixed npm audit vulnerabilities across packages.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/documentation_proposal.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/regression_report.md, .github/PULL_REQUEST_TEMPLATE.md, .vscode/settings.json, CODE_OF_CONDUCT.md, README.md, cli/generator-op-microservice/README.md, cli/generator-op-microservice/generators/microservice/templates/README.md, packages/feedback-spa/README.md, packages/home-spa/README.md, packages/ssi-service/README.md
#153 
Rectified all lint issues in the following files:-
No
=> fix(#153): Fixed all markdown lint issues.

packages/home-spa/src/index.html, packages/home-spa/src/js/controller.js, packages/home-spa/src/styles/common.scss, packages/home-spa/src/styles/main.scss, packages/home-spa/src/tests/index.spec.js
(feat#196) - Removed from tab and added in the page according to the designs and also updated the test cases
Implemented according to the new designs provided 
https://xd.adobe.com/view/efe4d47d-9981-422e-4e7f-d19446acdb31-99d5/
No
=> feat(#196) - Remove the tabs from home page and change to linear structure

packages/home-spa/src/404.html, packages/home-spa/src/img/Auth-illustration.svg, packages/home-spa/src/img/Feedback-illustration.svg, packages/home-spa/src/img/Notification-illustration.svg, packages/home-spa/src/img/Search-illustration.svg, packages/home-spa/src/img/User-profile-illustration.svg, packages/home-spa/src/index.html, packages/home-spa/src/js/controller.js, packages/home-spa/src/microservice-details.html, packages/home-spa/src/mocks/stub.js, packages/home-spa/src/styles/common.scss, packages/home-spa/src/styles/main.scss, packages/home-spa/src/tests/404.spec.js, packages/home-spa/webpack.config.js
Some basic optimizations and added ssi comment in the head of 404, microservice and index page
A microservice details page with more information that the cards, about each of the microservices.
No
=> feat(#200) - Microservice details page in home-spa

packages/user-service/package-lock.json, packages/user-service/package.json, packages/user-service/service.ts
Converted the existing the schema to the federated schema which is compaitable with the API gateway. It contains the support for cross querying with the multiple endpoints.
Yes
N/A
=> refactor : Converted the existing graphql schema to federated mode

packages/api-gateway-service/.env.example, packages/api-gateway-service/.gitignore, packages/api-gateway-service/README.md, packages/api-gateway-service/jest.config.js, packages/api-gateway-service/package-lock.json, packages/api-gateway-service/package.json, packages/api-gateway-service/service.ts, packages/api-gateway-service/src/e2e/api-gateway.spec.ts, packages/api-gateway-service/src/helpers.ts, packages/api-gateway-service/src/types.d.ts, packages/api-gateway-service/tsconfig.json, packages/api-gateway-service/tslint.json, packages/api-gateway-service/webpack.common.js, packages/api-gateway-service/webpack.dev.js, packages/api-gateway-service/webpack.prod.js
API Gateway for the One Platform which creates a unique bridge for multiple microservices. and creates a single endpoint for multiple microservices
Yes
N/A
=> feat: API gateway for the One Platform

cli-init.sh, cli/generator-op-microservice/generators/microservice/templates/.env.example, cli/generator-op-microservice/generators/microservice/templates/gql.service.ts, cli/generator-op-microservice/generators/microservice/templates/package.json, cli/generator-op-microservice/generators/microservice/templates/rest.service.ts, cli/generator-op-microservice/generators/microservice/templates/src/e2e/gql.service.spec.ts, cli/generator-op-microservice/generators/microservice/templates/src/resolver.ts, cli/generator-op-microservice/generators/microservice/templates/src/typedef.graphql, cli/generator-op-microservice/generators/microservice/templates/src/types.d.ts, cli/generator-op-microservice/package-lock.json, cli/generator-op-microservice/package.json
- Included `cookie parser` with graphql template
- Fixed the indendation of code in mongo db support
- Binded the native route as the first route for the rest based service
- Included the apollo federation support in the CLI
> No
<details>
</details>
=> fix(cli): changed the CLI template options and added support for federation

packages/user-service/src/helpers.ts
Included reconnection param with ldap connection
No
NA
=> fix(#222): Added LDAP reconnection param to the ldap

packages/home-service/.env.example, packages/home-service/src/e2e/home.spec.ts, packages/home-service/src/e2e/mock.json, packages/home-service/src/resolver.ts, packages/home-service/src/schema.ts, packages/home-service/src/typedef.graphql, packages/home-service/src/types.d.ts
Added API services and test cases for HomeType
Added APIs to home-service for `list, create, update, delete`
No
=> feat(#220) - Creating CRUD for HomeType and MicroserviceDetailsType in the home-service

packages/home-spa/.env.example, packages/home-spa/src/js/controller.js, packages/home-spa/src/js/service.js, packages/home-spa/src/mocks/stub.js, packages/home-spa/src/styles/main.scss
feat(#229) - Integrated home-spa with graphql home-service
- Fetches SPA and microservice information form the home-service using the listHomeType query
No
=> feat(#229) - Backend integration for home-spa and home-service

packages/home-spa/package.json, packages/home-spa/src/contact-us.html, packages/home-spa/webpack.config.js
fix(#251) - Removed production mode from npm scripts and added SSI to conta…ct page
Added the necessary build optimizations except removing the comments
No
=> fix(#251) - Home SPA build config removes the SSI include comments from the exported html files

cli/generator-op-microservice/generators/microservice/templates/README.md, cli/generator-op-microservice/generators/microservice/templates/package.json, cli/generator-op-microservice/generators/microservice/templates/webpack.common.js, cli/generator-op-microservice/generators/microservice/templates/webpack.dev.js, cli/generator-op-microservice/generators/microservice/templates/webpack.prod.js, packages/api-gateway-service/README.md, packages/api-gateway-service/package.json, packages/api-gateway-service/webpack.common.js, packages/api-gateway-service/webpack.dev.js, packages/api-gateway-service/webpack.prod.js, packages/feedback-service/README.md, packages/feedback-service/package.json, packages/feedback-service/webpack.common.js, packages/feedback-service/webpack.dev.js, packages/feedback-service/webpack.prod.js, packages/home-service/README.md, packages/home-service/package.json, packages/home-service/webpack.common.js, packages/home-service/webpack.dev.js, packages/home-service/webpack.prod.js, packages/user-service/README.md, packages/user-service/package-lock.json, packages/user-service/package.json, packages/user-service/webpack.common.js, packages/user-service/webpack.dev.js, packages/user-service/webpack.prod.js
Had removed the nodemon plugin before as it was interfering with the production build.
But that broke then local dev environment.
So added it back and made sure that it only works during development.
No
N/A
=> patch(cli): Added nodemon plugin back to the webpack config

packages/home-spa/src/js/controller.js, packages/home-spa/src/tests/contact-us.spec.js, packages/home-spa/src/tests/index.spec.js, packages/home-spa/src/tests/microservice-details.test.js
fix(#259) - Added test cases for home-spa contact-us and microservice…details page
Added test cases to home-spa
No
=> Unit tests for contact-page, microservice details page and and service getData

packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/feedback-service/service.ts, packages/feedback-service/src/e2e/feedback.spec.ts, packages/feedback-service/src/helpers.ts, packages/feedback-service/src/resolver.ts, packages/feedback-service/src/schema.ts
Updated code as per tslint coding standard.
No
<details>
</details>
=> Fix(#303):- clean backend code.

packages/api-gateway-service/package-lock.json, packages/api-gateway-service/service.ts, packages/api-gateway-service/src/helpers.ts
This PR provides the support for authoriation which decodes the incoming JWT token and append the decoded data to the current API request
Yes
N/A
=> feat:ONEPLAT-170, 172, 173 Authorization support in API gateway as a middleware

packages/home-service/src/e2e/home.spec.ts, packages/home-service/src/e2e/mock.json, packages/home-service/src/resolver.ts, packages/home-service/src/schema.ts, packages/home-service/src/typedef.graphql, packages/home-service/src/types.d.ts
fix/#285 - Added owners array to types and also added data to update home type
Added owners to types and fixed naming errors
```
Lint errors are possibly due to not installing node_modules
```
No
=> fix/#285 - Lint errors and name fixes, also add owners for home-service

packages/user-service/src/e2e/user.spec.ts, packages/user-service/src/resolver.ts, packages/user-service/src/typedef.graphql
This PR provides the API support for fetch users by rhatUUID, name, uid and all
No
N/A
<details>
</details>
=> feat(api): Included support for API query for additional parameters

cli/generator-op-microservice/generators/microservice/templates/.env.example, cli/generator-op-microservice/generators/microservice/templates/gql.service.ts, cli/generator-op-microservice/generators/microservice/templates/rest.service.ts, docker-compose.yml, packages/api-gateway-service/.env.example, packages/api-gateway-service/service.ts, packages/feedback-service/.env.example, packages/feedback-service/service.ts, packages/home-service/.env.example, packages/home-service/service.ts, packages/user-service/.env.example, packages/user-service/service.ts
Changed the HTTPs server mode to http server mode and removed other dependencies related to it. and updated the docker file
No
<details>
</details>
=> fix:332 - Changed the server from https to http mode for all microservices.

packages/user-service/src/cron.ts, packages/user-service/src/resolver.ts, packages/user-service/src/schema.ts, packages/user-service/src/typedef.graphql, packages/user-service/src/types.d.ts
Converted the timestamp object type in to normalized form 
No
=> fix - 316: Changed the timestamp Object type for user microservice

.gitignore, README.md, docker-compose.yml, packages/ssi-service/jest.config.js, packages/ssi-service/package-lock.json, packages/ssi-service/package.json, packages/ssi-service/public/index.html, packages/ssi-service/src/default.html, packages/ssi-service/src/nav/api.js, packages/ssi-service/src/nav/auth.js, packages/ssi-service/src/nav/nav.css, packages/ssi-service/src/nav/nav.js, packages/ssi-service/webpack.config.js
Implemented SSO auth and the user - profile drawer;
Also,
* integrated App Drawer with the Home Service API for getHomeTypeBy
* fixed some dependencies upgrades
* updated the docker-compose.yml
* updated README.md to include steps to use docker-compose for local development
No
<details>
* User Profile Drawer
* App Drawer (after integrating it with Home Service API
</details>
=> feat(sso-auth): Implemented the SSO Auth in the header component (SSI)

packages/user-service/src/helpers.ts, packages/user-service/src/resolver.ts
Included the helper function for the ldap and user bridge which enable to pull data from ldap and create it in database by using the existing LDAP helper function
No
N/A
=> feat(#338): Support on the `getUserBy` method which enables to talk to ldap to pull data if data is not available

packages/feedback-spa/src/index.html, packages/home-spa/src/404.html, packages/home-spa/src/contact-us.html, packages/home-spa/src/index.html, packages/home-spa/src/microservice-details.html, packages/notification-spa/src/index.html
Resolves #366 
Updated the SSI header include snippet to all existing One Platform SPAs.
No
=> feat(#366): Updated SSI include snippet to all SPA heads.

packages/home-service/src/helpers.ts, packages/home-service/src/resolver.ts
fix(#365) - Added .lean() in the resolver
Added .lean() so that find() would return a simple POJO and not a mongoose object
No
=> Use .lean() in home-service

packages/ssi-service/.env.example, packages/ssi-service/package.json, packages/ssi-service/src/nav/nav.js, packages/ssi-service/webpack.config.js
- Renamed `SSI_HOSTNAME` to `ASSETS_HOST`
- Changed the package name to `@one-platform/ssi-templates`
- Updated the package version to 0.0.1-prerelease.01
- Published the package to npmjs
No
N/A
=> fix(ssi-assets): Renamed SSI_HOSTNAME to ASSETS_HOST for brevity

packages/notifications-service/package-lock.json, packages/notifications-service/package.json, packages/notifications-service/service.ts
#362
Included the subscriptions support notifications microservice endpoint configuration.
Yes
Cli Generator and all the microservices end point has changed with subscription support
N/A
=> fix(#362): Enabled microservice endpoint for the new gateway config

docker-compose.yml, packages/ssi-service/.npmignore, packages/ssi-service/Dockerfile, packages/ssi-service/package-lock.json, packages/ssi-service/src/feedback-panel/feedback.js, packages/ssi-service/src/nav/auth.js, packages/ssi-service/src/nav/nav.js, packages/ssi-service/tests/setupJest.js
Fixed some platform specific bugs for firefox, and some quick fixes for the feedback panel API integration.
And prepared for use with SPAship.
No.
N/A
=> fix(ssi-templates): SSI template hotfixes for firefox and spaship

packages/home-service/README.md, packages/home-service/src/e2e/home.spec.ts, packages/home-service/src/e2e/mock.json, packages/home-service/src/schema.ts, packages/home-service/src/typedef.graphql, packages/home-service/src/types.d.ts
Added active field in the home-service
Added active field in schema
No
=> feat(#403) - Flag to check if spa/microservice is enabled or disabled

packages/home-spa/package.json, packages/home-spa/src/app.js, packages/home-spa/src/index.html, packages/home-spa/src/js/controller.js, packages/home-spa/src/mocks/stub.js, packages/home-spa/src/styles/main.scss
fix(#362) - Changed home-spa according to the new designs and added better mock data
Changed the home-spa for better UX and added better mock data
No
=> fix(#362) - Home Page Design Improvements

packages/feedback-spa/src/app/apollo.config.ts, packages/feedback-spa/src/index.html
Add base URL for feedback (/feedback)
No
<details>
</details>
=> Feat(#375):-Add base url for feedback

packages/home-service/package-lock.json, packages/home-service/src/typedef.graphql
Removed non-nullable expressions from grahpql
No
NA
=> fix(#413) - Remove non-nullable from home-service

packages/home-spa/src/js/service.js
Added authorization in the headers for fetch
No
NA
=> fix(#410) - Home-SPA should be able to fetch information form the API gateway 

packages/api-gateway-service/service.ts
Included the default cors option in the gateway headers
No
N/A
=> fix:371 Updated the Cors options to default

packages/feedback-service/src/resolver.ts
Add label in Jira ticket if its being created from feedback module so in listing page we need to fetch all the the we can pass JQL query to make search faster no need to fetch all the jira.
No 
<details>
</details>
=> Feat(#395):- Add labels to jira ticket while creating it from feedback module

packages/feedback-spa/src/app/feedback/feedback-item/feedback-item.component.html, packages/feedback-spa/src/app/feedback/feedback.ts, packages/feedback-spa/src/app/feedback/home/feedback-home.component.html, packages/feedback-spa/src/app/feedback/home/feedback-home.component.ts
Updated feedback-spa code as per jira integration and feedback-service schema change like using ticketId instead of iid(gitlab)  and removed timestamp from feedback-spa
No
<details>
</details>
=> Fix(#359) Adjust feedback-spa code as per Jira integration to show assignee and createdBy

cli/generator-op-microservice/generators/microservice/templates/gql.service.ts, packages/api-gateway-service/service.ts, packages/feedback-service/service.ts, packages/home-service/service.ts, packages/notifications-service/service.ts, packages/user-service/service.ts
This fix includes the logging feature aswell as the stiching between multiple sources . this resolves the cross querying between microservices.
No
Shows the support of cross querying the microservices.
<details>
</details>
=> fix(397)-Fixed the schema merging issue on remote loading and the logging on the gateway

packages/home-service/src/e2e/home.spec.ts, packages/home-service/src/helpers.ts, packages/home-service/src/resolver.ts, packages/home-service/src/typedef.graphql
Fixed errors for null response
Added UserType in the fragment to fetch from user-service
No
NA
=> fix(#449) - Testing and fixing home-service for errors 

packages/api-gateway-service/service.ts
Enabled the playground in API gateway.
=> fix:403 Playground enabled for the api gateway

docker-compose.yml, packages/home-spa/src/app.js, packages/home-spa/src/index.html, packages/home-spa/src/js/controller.js, packages/home-spa/src/js/service.js, packages/home-spa/src/mocks/stub.js, packages/home-spa/src/styles/common.scss
Added view application and target _blank
Added view application and target _blank
No
=> fix(#452) - Home SPA needs improvement on the links

packages/notifications-service/src/notificationConfig/resolver.ts
Fix for the NotificationConfig.source sub fields that get populated from the Home Service.
And cleaned up the notificationConfig.source populate logic.
No.
N/A
=> fix(notifications-service): Validation for Notification Config source

packages/notifications-service/src/__tests__/notificationConfig.spec.ts, packages/notifications-service/src/notificationConfig/resolver.ts, packages/notifications-service/src/notificationConfig/schema.ts, packages/notifications-service/src/notificationConfig/typedef.graphql
Added validation for empty source response, and fixed the issue where the source object was being returned as null.
No
N/A
=> fix(notifications-service): Patch for the NotificationConfig.source populate

packages/notifications-service/src/notificationConfig/resolver.ts, packages/notifications-service/src/notificationConfig/schema.ts, packages/notifications-service/src/notificationConfig/typedef.graphql
Added a custom cast to `_id` in `getNotificationConfigsBy` endpoint.
Yes.
N/A
=> fix(notification-service): Added id field in the getNotificationConfigsBy selectors

packages/home-spa/src/js/controller.js, packages/home-spa/src/microservice-details.html, packages/home-spa/webpack.config.js
Added check in home-spa and also added loader where it was necessary
No
=> fix/#481 - Home-SPA shows mock data instead of backend data

packages/feedback-service/src/helpers.ts, packages/feedback-service/src/resolver.ts
Once feedback submitted it was not showing successful submitted message because from backend it was not returning proper response, feedback was getting created only thing it was not showing submitted message on UI.
No
<details>
</details>
=> Fix(#394):- Feedback not submitted

packages/feedback-service/src/resolver.ts
There was a bug in feedback-spa if updatedby has no value it will through and error so updated if condition read it only when it exist
No
<details>
</details>
=> Bug(#468):- Console error in feedback module

.vscode/settings.json, README.md, deploy.sh, deploy.test.sh, one-platform.code-workspace, package-lock.json, package.json, packages/feedback-spa/angular.json, packages/feedback-spa/package-lock.json, packages/feedback-spa/package.json, packages/feedback-spa/src/app/feedback/feedback-item/feedback-item.component.html, packages/feedback-spa/src/app/feedback/feedback-item/feedback-item.component.ts, packages/feedback-spa/src/app/feedback/home/feedback-home.component.html, packages/feedback-spa/src/app/feedback/home/feedback-home.component.ts, packages/feedback-spa/src/environments/environment.dev.ts, packages/feedback-spa/src/environments/environment.env.example, packages/feedback-spa/src/environments/environment.prod.ts, packages/feedback-spa/src/environments/environment.qa.ts, packages/feedback-spa/src/environments/environment.stage.ts, packages/feedback-spa/src/environments/environment.ts, packages/notification-spa/angular.json, packages/notification-spa/package-lock.json, packages/notification-spa/package.json, packages/user-profile-spa/angular.json, packages/user-profile-spa/package-lock.json, packages/user-profile-spa/package.json, packages/user-profile-spa/src/index.html
Resolves #454 
1. Fixed SPA build locations to /dist.
2. Updated all Angular SPA builds with base-href values.
3. Added SSI to User Profile SPA.
4. Updated package-lock for User Profile SPA. 
5. Implemented package deployment script.
6. Fixed incompatible typescript dependency in feedback-spa.
7. Added env.example to environments.
8. Renamed roverURL to userProfileURL within feedback-spa.
9. Disabled auto format on save.
No
=> feat(#454): Implemented package deployment script.

packages/feedback-service/src/resolver.ts, packages/feedback-service/src/schema.ts
Graphql does not support hyphen in query alias so remove it
No
<details>
</details>
=> Bug(/#497):-Remove hyphen from graphql alias

docker-compose.yml, packages/ssi-service/.env.example, packages/ssi-service/README.md, packages/ssi-service/package-lock.json, packages/ssi-service/package.json, packages/ssi-service/src/feedback-panel/feedback.css, packages/ssi-service/src/feedback-panel/feedback.js, packages/ssi-service/src/nav/api.js, packages/ssi-service/src/nav/auth.js, packages/ssi-service/src/nav/nav.css, packages/ssi-service/src/nav/nav.js, packages/ssi-service/tests/feedback-panel.spec.js, packages/ssi-service/tests/nav.spec.js, packages/ssi-service/webpack.config.js
- Refactored the SSI Components using Lit Elements
- Added Pop-up notification support (with an exposed Helper function to show a toast message from any SPA)
- Fixed some issues related to App Drawer and Notifications
- Added Feedback Panel enhancements
No
<details>
1. Single Pop-up Notification
2. Multiple Pop-up Notifications (Max. 5 supported)
3. Notifications Drawer
4. App Drawer (reduced the icon size, and resized the grid to include 8 columns in a row)
5. Feedback Panel
6. Submit Feedback Form
7. Unit Test Report
</details>
=> feat(ssi-service): Refactored the OpNav using LitElements & Enhancements for OpFeedbackPanel

packages/ssi-service/src/feedback-panel/feedback.css, packages/ssi-service/src/feedback-panel/secrets.example.json, packages/ssi-service/src/nav/nav.js, packages/ssi-service/tests/feedback-panel.spec.js, packages/ssi-service/tests/nav.spec.js
And also fixed the warnings during unit tests.
No.
N/A
=> fix(ssi): Minor fixes for Feedback Form and App Drawer icons

packages/feedback-spa/src/app/feedback/home/feedback-home.component.ts
These changes will handle unassigned Jira ticket.
No 
<details>
</details>
=> Bug(/#532):-Handle unassigned jira ticket

packages/api-gateway-service/package-lock.json, packages/api-gateway-service/package.json, packages/api-gateway-service/service.ts
- Get access to the API has revoked.
No
N/A
=> fix(gateway): Fixed the access issues on the API Gateway

packages/home-service/src/schema.ts
Added default values and error checks for the home-service
No
=> fix(#504): Home service improvements 

packages/notifications-service/src/broadcaster.ts, packages/notifications-service/src/engine.ts, packages/notifications-service/src/resolver.ts, packages/notifications-service/src/typedef.graphql, packages/notifications-service/src/types.d.ts, packages/ssi-service/src/nav/api.js, packages/ssi-service/src/nav/nav.js
The targets argument in listArchivedNotifications restricts the results to be specific to the given targets (users/rover groups), which helps avoid spamming all the users with everyone's notifications.
Yes
The change in the graphql query may cause the Notification Drawer to behave unexpectedly. So we will have to redeploy the SSI Nav again.
N/A
=> enhancement(notifications-service): Added targets to the listArchivedNotifications

packages/ssi-service/README.md, packages/ssi-service/src/nav/nav.css, packages/ssi-service/src/nav/nav.js
- Added new variants for the toast messages
- Created helper functions for each toast variant
- And some hotfixes for Nav menu states
No
<details>
- Different toast variants
</details>
=> feat(ssi): Contextual theming for Toast messages

docker-compose.yml, packages/feedback-spa/src/index.html, packages/home-spa/src/404.html, packages/home-spa/src/contact-us.html, packages/home-spa/src/index.html, packages/home-spa/src/microservice-details.html, packages/notification-spa/src/index.html, packages/ssi-service/.env.example, packages/ssi-service/README.md, packages/ssi-service/package-lock.json, packages/ssi-service/package.json, packages/ssi-service/src/auth.js, packages/ssi-service/src/default.html, packages/ssi-service/src/feedback-panel/feedback-lit.js, packages/ssi-service/src/nav/nav.js, packages/ssi-service/tests/feedback-panel.spec.js, packages/ssi-service/tests/setupJest.js, packages/ssi-service/webpack.config.js, packages/user-profile-spa/src/index.html
- Changed the auth library to basic keycloak-js
- Moved the SSI Include snippet to the html body for all SPAs
- And added a loader to the SSI
No
<details>
- The Loader
</details>
=> fix(ssi): Changed the auth library to basic keycloak-js

packages/ssi-service/src/feedback-panel/feedback.js
A small patch for updating the SPA selection dropdown in "Share Feedback" form when the pop-out form is opened before the SPA list could be fetched from the API.
No
N/C
=> fix(ssi): Dynamic update for SPA dropdown in Feedback form

.github/workflows/notify.yml
Added Notifications to One Platform Developers channel when a pull request is opened
=> chore: Added Gchat Channel Notifications

packages/api-gateway-service/.env.example, packages/api-gateway-service/service.ts, packages/api-gateway-service/src/helpers.ts
- Patch for auth middleware for Subscriptions
- Also removed network call for Keycloak pubkey, and used env variable
- And some code cleanup
Yes
When redeploying the API Gateway, we need to make sure to set the KEYCLOAK_PUBKEY env variable.
N/A
=> fix(api-gateway): API Gateway auth fixes and some code cleanup

packages/home-spa/src/js/controller.js, packages/home-spa/src/js/service.js
Removed the Auth token handling overhead as it is no longer needed, and may potentially break the UI.
No.
N/A
=> fix(home-spa): Patch for Request authorization in Home controller

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/404.html, packages/home-spa/src/app.js, packages/home-spa/src/contact-us/index.html, packages/home-spa/src/index.html, packages/home-spa/src/js/controller.js, packages/home-spa/src/styles/common.scss, packages/home-spa/src/styles/main.scss, packages/home-spa/webpack.config.js
Changed some image links and some tweaks to the build process for the image assets.
No
N/A
=> fix(home-spa): Fixed some broken img assets and links

packages/ssi-service/public/index.html, packages/ssi-service/src/default.html, packages/ssi-service/src/nav/api.js, packages/ssi-service/src/nav/nav.js
A clean way to provide auth token to the websocket requests for GraphQL subscriptions.
No.
N/A
=> fix(ssi): Added auth token to websocket connection params

packages/home-spa/src/404.html, packages/home-spa/src/contact-us/index.html, packages/home-spa/src/index.html, packages/home-spa/src/js/controller.js, packages/home-spa/src/styles/main.scss
Added the fixes to show SPAs only on the apps in spotlight section
No
=> fix(#617) -  Incorrect links and other fixes for beta and qa instances

packages/ssi-service/package-lock.json, packages/ssi-service/package.json, packages/ssi-service/src/nav/nav.js, packages/ssi-service/webpack.config.js
Empty notification toasts, and ssi package version bump
No
No
=> Error handling for subscriptions, and version bump

docker-compose.yml, packages/user-group-spa/.gitignore, packages/user-group-spa/README.md, packages/user-group-spa/package-lock.json, packages/user-group-spa/package.json, packages/user-group-spa/public/.htaccess, packages/user-group-spa/public/config.js, packages/user-group-spa/public/index.html, packages/user-group-spa/src/App.css, packages/user-group-spa/src/App.jsx, packages/user-group-spa/src/App.test.js, packages/user-group-spa/src/components/Form.jsx, packages/user-group-spa/src/components/Group.jsx, packages/user-group-spa/src/components/Home.jsx, packages/user-group-spa/src/components/NotFound.jsx, packages/user-group-spa/src/components/User.jsx, packages/user-group-spa/src/index.css, packages/user-group-spa/src/index.js, packages/user-group-spa/src/serviceWorker.js, packages/user-group-spa/src/services/FetchClient.js, packages/user-group-spa/src/services/GqlQueries.js, packages/user-group-spa/src/services/GroupsAPI.js, packages/user-group-spa/src/setupTests.js
> #### Dependent on #626 
- Includes React App
- Groups Listing Page
- Add/Edit Group Form
- Group Details Page
- User Details Page
No
<details>
- Group Listing page
- Group Details
- Add/Edit Group Form
- User Profile Details
</details>
=> feat(user-group-spa): 👥 Implementation of User Group SPA

cli/generator-op-microservice/generators/microservice/index.js
Added default git selections for yeoman
No
=> feat(#55) - Pull native git config to the cli

cli/generator-op-microservice/generators/microservice/templates/webpack.dev.js, cli/generator-op-microservice/generators/microservice/templates/webpack.prod.js, packages/api-gateway-service/webpack.dev.js, packages/api-gateway-service/webpack.prod.js, packages/feedback-service/webpack.dev.js, packages/feedback-service/webpack.prod.js, packages/home-service/webpack.dev.js, packages/home-service/webpack.prod.js, packages/notifications-service/webpack.dev.js, packages/notifications-service/webpack.prod.js, packages/search-service/webpack.dev.js, packages/search-service/webpack.prod.js, packages/user-group-service/webpack.dev.js, packages/user-group-service/webpack.prod.js
Updated the import on the microservices  of the webpack package.
Yes
=> fix-687: Updated microservices with fix as resulted from the upgrade on webpack 

.github/workflows/codeql-analysis.yml
#690 
Setup the CodeQL Analysis workflow for GitHub to enable Code Scanning for the repo.
No
=> chore(#690): Setup Code Scanning

packages/user-group-spa/package-lock.json, packages/user-group-spa/package.json, packages/user-group-spa/src/App.jsx, packages/user-group-spa/src/components/Form.jsx, packages/user-group-spa/src/components/Group.jsx, packages/user-group-spa/src/components/Home.jsx, packages/user-group-spa/src/components/NotFound.jsx, packages/user-group-spa/src/components/User.jsx, packages/user-group-spa/src/context/BreadcrumbContext.jsx, packages/user-group-spa/src/index.js
- Added `opc-header` to the User Group SPA
- And created a context helper for updating the breadcrumbs
No.
<details>
| Page | Screenshot |
|---|---|
| User Group Home | <img width="1920" alt="Screenshot 2020-09-17 at 8 01 23 PM" src="https://user-images.githubusercontent.com/19623278/93486723-26009c80-f922-11ea-8483-0a4c8a30d3f5.png"> |
| Add New Group | <img width="1920" alt="Screenshot 2020-09-17 at 8 11 42 PM" src="https://user-images.githubusercontent.com/19623278/93486932-5ea07600-f922-11ea-84f5-0b0b70d6631a.png"> 
| Edit Group | <img width="1920" alt="Screenshot 2020-09-17 at 8 10 34 PM" src="https://user-images.githubusercontent.com/19623278/93486974-6d872880-f922-11ea-9dc3-df3fc944c6dd.png"> |
| Group Details | <img width="1920" alt="Screenshot …
=> feat(user-group-spa): Added opc-header to the User Group SPA

packages/feedback-spa/package.json
Reverted the apollo-angular conflicted packaged version in code.
No
N/A
=> fix: 659 Updated the package.json with conflicted versions of apollo-angular

packages/search-spa/src/app/search/search.component.html, packages/search-spa/src/app/search/search.component.scss
Removed the bordersin search listing and reduced the font sizes of the listing.
No
<details>
</details>
=> fix:721 - Removed the borders in search listing

packages/search-spa/src/app/search/search.component.html
Fixed the timestamp intepolation issue on the search view. and updated the ids for the search filters
No
N/A
=> fix:(#4902) - Fixed the interpolation of timestamp in the search ui

README.md, package.json, platform.js
Added README and lerna in scripts
No
N/A
=> fix(#718) - Installation documentation for using One Platform

cli/generator-op-microservice/generators/microservice/templates/package.json, packages/api-gateway-service/package-lock.json, packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/home-service/package-lock.json, packages/home-service/package.json, packages/notifications-service/package-lock.json, packages/notifications-service/package.json, packages/search-service/package-lock.json, packages/search-service/package.json, packages/user-group-service/package-lock.json
Fixed Microservice build failing due to the missing types of ```@types/express``` package in microservices.
No
N/A
=> fix:770 - Microservice build failing due to missing typescript package

packages/ssi-service/package.json, packages/ssi-service/src/nav/nav.js
Fixed the logout functionality to the logout button in the SSI. This enables the User to logout from One Platform.
No
N/A
=> fix:682 - Fixed the Logout functionality issue to the header menu options

packages/search-spa/package-lock.json, packages/search-spa/package.json, packages/search-spa/src/app/graphql.module.ts
Apollo Client configuration on search spa has updated with the changes on ```apollo-client```.
No
N/A
=> fix:789 - Apollo Client configuration has updated with the changes on apollo-client

packages/home-spa/webpack.config.js
Added public path to webpack
No
=> fix(#772) - Add a public path to home-spa build config

packages/documentation-spa/docs/apps/internal/ssi-service/ssi-service.md, packages/ssi-service/.env.example, packages/ssi-service/src/default.html, packages/ssi-service/src/feedback-panel/api.js, packages/ssi-service/src/feedback-panel/feedback.js, packages/ssi-service/src/feedback.slim.html, packages/ssi-service/webpack.config.js
- Created new html template for feedback component
- And changed the ionicons cdn to cloudflare
No
N/A
=> feat(ssi): Created new template for feedback component

packages/common/footer.json, packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/app.js, packages/notification-spa/src/main.ts
=> fix(#794) - Change footer links for and other fixes for angular base SPAs

packages/user-group-spa/src/index.js
ONEPLAT-895
Fixing the API failing issue in User Groups SPA.
No
<details>
</details>
=> Fix: Adding check to initialise app after successful login.

packages/user-group-spa/public/index.html
#813
Ionicons was not loading in SSI header the user groups SPA, The issue was that Ionicons was being imported multiple times, once in SSI and again in SPA. 
No
<details>
</details>
=> Fix(#813): Ionicons load issue in SSI header and User Group SPA

packages/user-group-service/src/api-keys/resolver.ts, packages/user-group-service/src/api-keys/typedef.graphql, packages/user-group-service/src/groups/resolver.ts, packages/user-group-spa/src/services/GqlQueries.js
- Adds full accessToken to the `createAPIKey` and `revokeAPIKey` response
- And some fixes for User Group API and list page
No.
N/A
=> fix(user-groups): Hotfixes for User Group API and list page

docker-compose.yml, packages/feedback-spa/src/index.html, packages/home-spa/src/404.html, packages/home-spa/src/contact-us/index.html, packages/home-spa/src/index.html, packages/notification-spa/src/index.html, packages/search-spa/src/index.html, packages/ssi-service/.env.example, packages/ssi-service/public/index.html, packages/user-group-spa/public/index.html, packages/user-profile-spa/src/index.html
Changes the default ssi template path to `/.ssi/*` instead of `/.include/*`
No.
N/A
=> fix(ssi-path): Changes the ssi default path to /.ssi

packages/documentation-spa/blog/2020-10-30-announcing-one-platform-general-availability.md, packages/documentation-spa/blog/2020-12-08-state-of-one-platform-nov-2020.md, packages/documentation-spa/docs/microservices/notifications/get-started.md, packages/documentation-spa/docs/microservices/notifications/notifications-service.md, packages/documentation-spa/package-lock.json, packages/documentation-spa/package.json, packages/documentation-spa/sidebars.js
=> docs(notifications-service): Added Get Started Guide for Notifications Service

packages/documentation-spa/blog/2020-12-08-state-of-one-platform-dec-2020.md
Adds the "State of One Platform - Dec 2020" Blog Post.
=> docs(blog): Publishes State of One Platform - Dec 2020

packages/documentation-spa/blog/2021-01-08-state-of-one-platform-dec-2020.md
N/A
Updates OKRs of the January State of One Platform blog post.
No
=> docs(blog): Updates OKRs of the January State of One Platform blog post.

packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/feedback-service/src/resolver.ts, packages/home-service/package-lock.json, packages/home-service/package.json, packages/home-service/src/resolver.ts, packages/notifications-service/package-lock.json, packages/notifications-service/package.json, packages/user-group-service/package-lock.json, packages/user-group-service/package.json, renovate.json
Renovate PRs automerge has disabled in one platform
No
N/A
=> Disabled the renovate automerge on minor changes and fixed the mongoose version and build issues

packages/home-service/package-lock.json, packages/home-service/package.json, packages/home-service/src/resolver.ts, packages/home-service/src/schema.ts, packages/home-service/src/typedef.graphql, packages/home-service/src/types.d.ts
-  Added applicationType to home-service schema
No
=> fix(#860) - Implement the categorisation designs for the platform SSI (Part 1)

packages/home-service/package-lock.json, packages/home-service/src/e2e/mock.json, packages/home-service/src/resolver.ts, packages/home-service/src/schema.ts, packages/home-service/src/typedef.graphql
=> Fix/#866 - Create provision to manage contacts related to SPA in home service

packages/ssi-service/src/nav/api.js, packages/ssi-service/src/nav/nav.css, packages/ssi-service/src/nav/nav.js
Added implementation for SSI categorization design
No
=> fix(#873) - Implement the categorisation designs for the platform SSI

packages/documentation-spa/blog/2021-02-08-state-of-one-platform-jan-2021.md
N/A
Updates OKRs of the January State of One Platform blog post.
No
=> Docs(blog): January 2021 State of One Platform blog post 

packages/search-spa/package-lock.json, packages/search-spa/package.json, packages/search-spa/src/app/app.component.spec.ts, packages/search-spa/src/app/app.service.ts, packages/search-spa/src/app/search/search.component.html, packages/search-spa/src/app/search/search.component.spec.ts, packages/search-spa/src/app/search/search.component.ts, packages/search-spa/src/app/testing/mocks/result.mock.ts, packages/search-spa/src/main.ts, packages/search-spa/src/module.d.ts
SPA fixes for handling the data from the backend data with new change from the data from scripts. Aslo the typescript version has synced with other dependencies.
No
<details>
</details>
=> 949 - Fixed the SPA Validation as part of data updation and synced the dependencies

renovate.json
Changes the renovate PR frequency to monthly on the first monday of every month.
No.
N/A
=> chore(renovate-schedule): Changes renovate schedule to monthly

packages/feedback-service/src/resolver.ts, packages/feedback-service/src/schema.ts, packages/feedback-service/src/typedef.graphql, packages/feedback-service/src/types.d.ts
Seperated the Input type for bug and fixed the graphql type
No
N/A
=> fix - 978: Included the categorization based on the input entry of feedback and seperated bug field

.gitignore, cypress.env.example.json, cypress.json, e2e/helper/apps.list.js, e2e/integration/homePage.js, package-lock.json, package.json
ONEPLAT-1014
Added tests for Homepage.
NO
<details>
</details>
=> Feat(#1014): Added e2e tests for Home SPA

e2e/integration/ssi.js, package.json
added tests for ssi
No
<details>
</details>
=> added tests for ssi

.github/workflows/build-api-gateway.yml
The destination namespace for the api-gateway image was set as `deshmukhmayur` instead of `1-Platform` in the previous commit.
No.
N/A
=> hotfix(gh-actions): Changes api-gateway image namespace to 1-Platform

packages/documentation-spa/blog/2021-02-08-state-of-one-platform-jan-2021.md, packages/documentation-spa/blog/2021-03-10-state-of-one-platform-feb-2021.md
N/A
Updates February State of One Platform blog post.
No
=> Docs(blog): February 2021 State of One Platform blog post

packages/documentation-spa/blog/2021-03-10-state-of-one-platform-feb-2021.md
N/A
Updates February State of One Platform blog post.
No
=> Feat - Feb blog: Updated OKR description.

packages/documentation-spa/blog/2021-03-10-state-of-one-platform-feb-2021.md
N/A
Correction in the column list structure under OKRs.
No
=> Docs(blog): February 2021 blog - Correction in list in table column.

packages/feedback-spa/public/index.html, packages/feedback-spa/src/components/ListFeedback.vue, packages/feedback-spa/src/views/Home.vue
- Locked the patternfly version to 4.90.5
- Fixed the open/close issie of the feedback list. 
No
N/A
=> fix(1089): Locked the patternfly version to 4.90.5 nd fixed the open/close property of the modal.

packages/search-service/src/search-mapping/cron.ts, packages/search-service/src/search-mapping/schema.ts, packages/search-service/src/search-mapping/typedef.graphql, packages/search-service/src/types.d.ts
Fixed the search title automation and url parsing with the script.
No
N/A
=> (fix:949) - Fixed the URL and title Parameter formatting issues with script

packages/feedback-spa/src/views/Home.vue
Fixed the search results for Feedback SPA 
No
N/A
=> (fix:1089,1090) - Fixed the search results for the feedback SPA

packages/documentation-spa/blog/2021-04-12-state-of-one-platform-mar-2021.md
ONEPLAT-1118
Updates March 2021 State of One Platform blog post.
No
=> Docs(blog): March 2021 State of One Platform blog post

cypress.json, e2e/integration/homePage.js, e2e/integration/searchtests.js, package-lock.json, package.json
ONEPLAT-1062
Added tests for search
No
<details>
</details>
=> Feat(#1062): Added tests for search

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/index.html, packages/home-spa/src/js/controller.js
-Added an event listener to show the DOM contents only when all the page is loaded
No
https://user-images.githubusercontent.com/12994292/113139655-076e4d00-9245-11eb-8102-373e220a6852.mov
=> fix(#920) - Layout styles load 1-2 seconds after page load on the One Platform Home Page

.github/workflows/notify.yml
n/a
chore: change notify workflow repo
No
n/a
=> chore: change notify workflow repo

packages/ssi-service/src/nav/api.js, packages/ssi-service/src/nav/nav.js
The app drawer appears empty due to error in the notifications query
Until the root error is fixed, this should serve as a temporary solution
No.
N/A
=> fix(ssi): Temporary fix for the blank app drawer issue

packages/home-spa/.htaccess, packages/home-spa/package-lock.json, packages/home-spa/src/home/home.html, packages/home-spa/src/home/home.js, packages/home-spa/src/home/home.scss, packages/home-spa/src/index.js, packages/home-spa/src/service/service.js, packages/home-spa/webpack.config.js
=> fix(#971) - Add "Deploy to One Platform" button on the home-page

packages/home-spa/src/index.js
Fixes ONEPLAT-1224
The report an issue button [in footer] is not toggling the feedback panel on home page.
No
=> fix(#1224): footer button[report-an-issue] toggle error

packages/developer-console-spa/src/App.css, packages/developer-console-spa/src/components/AddAppForm.tsx, packages/developer-console-spa/src/components/AppCard.tsx, packages/developer-console-spa/src/components/AppOverview.tsx, packages/developer-console-spa/src/components/Sidebar.tsx, packages/developer-console-spa/src/hooks/useAppAPI.ts, packages/developer-console-spa/src/utils/gql-queries/app-by-appid.ts, packages/developer-console-spa/src/utils/gql-queries/my-apps.ts, packages/developer-console-spa/src/utils/gql-queries/new-app.ts
- Changes to the graphql query for myApps
- some minor hotfixes
No.
N/A
=> fix(dev-console): Adds new appId and ownerId fields

.gitignore, e2e/helper/apps.list.js, e2e/integration/hometests.js
Fixed Home tests according to the UI changes
No
<details>
</details>
=> feat:e2e- Fixed Home tests according to the UI changes

packages/user-group-service/package.json, packages/user-group-spa/README.md, packages/user-group-spa/package.json, packages/user-group-spa/src/components/Form.jsx, packages/user-group-spa/src/components/Group.jsx, packages/user-group-spa/src/components/Home.jsx, packages/user-group-spa/src/components/User.jsx, packages/user-group-spa/src/services/GqlQueries.js, packages/user-group-spa/src/services/GroupsAPI.js
ONEPLAT-1142, ONEPLAT-1073
Updated the queries and mutation as per the changes in API
No
<details>
</details>
=> Feat#1142&1073: GraphQL query & mutation updates as per the API 

packages/user-group-service/src/users/resolver.ts
ONEPLAT-1252
Fix for getUserBy code to return _id field when the user is not present in the cache DB.
No
<details>
</details>
=> Fix: #1252: Fix for getUserBy code to return _id field when the user is not present in the cache DB

README.md, cli/generator-op-microservice/README.md
Fixes typos in READMEs.
No
<details>
</details>
=> docs(readme): fix typos

packages/documentation-spa/docs/microservices/user-groups/user-groups-service.md
ONEPLAT-1202
Updating user service documentation as per the latest implementation of Rover integration.
<details>
</details>
=> Feat: #1202: Updating user service documentation

packages/home-spa/src/contact-us/contact-us.js, packages/home-spa/src/contact-us/contact-us.scss, packages/home-spa/src/index.js, packages/home-spa/src/res/img/avatar.svg, packages/home-spa/src/service/service.js
Closes ONEPLAT-1226
* Converted hard-coded contact us list in one platform home-spa to user group api fetched list.
* List is sorted on alphabetical order of name.
No
<details>
</details>
=> feat(1226): changed hardcoded contact us list to user-group api list

packages/documentation-spa/docs/microservices/api-gateway/api-gateway.md, packages/documentation-spa/sidebars.js
Added documentation for the API Gateway.
No.
N/A
=> docs(api-gateway): Creates documentation for API Gateway

packages/lighthouse-service/src/audit-manager/resolver.ts, packages/lighthouse-service/src/audit-manager/typedef.graphql, packages/lighthouse-service/src/property-manager/resolver.ts, packages/lighthouse-service/src/property-manager/typedef.graphql, packages/lighthouse-spa/src/app/app.gql.ts, packages/lighthouse-spa/src/app/app.service.ts, packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts, packages/lighthouse-spa/src/app/dashboard/dashboard.service.ts, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts, packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.ts, packages/lighthouse-spa/src/app/home/components/home/home.component.ts
- fix(1302) - Type conflicts with apps service and lighthouse service
1. Fixed type conflict due to lighthouse schema with app service schema
2. Made changes to SPA with the service type definition changes
3. Better comments added
No
NA
=> fix(1302): fixed type conflicts with apps service and lighthouse service

packages/user-group-service/src/groups/resolver.ts, packages/user-group-service/src/helpers.ts, packages/user-group-service/src/users/resolver.ts
Fixed the types error on bootstraping the microservice.
No
N/A
=> (fix:1301) Fixed the types warnings and errors of user-group service

packages/feedback-service/src/helpers.ts, packages/feedback-service/src/resolver.ts, packages/search-service/src/search-config/helpers.ts, packages/search-service/src/search-config/resolver.ts, packages/search-service/src/search-config/typedef.graphql, packages/search-service/src/search-mapping/helpers.ts, packages/search-service/src/search-mapping/resolver.ts, packages/search-service/src/search-mapping/typedef.graphql
ONEPLAT-1287
- Improving the search index API 
- Search API helper modifications in Feedback service
Yes
<details>
</details>
=> Feat#1287: Improving the search index API & API helper modifications in Feedback service

cli/generator-op-microservice/generators/microservice/index.js, cli/generator-op-microservice/generators/microservice/templates/webpack.common.js, packages/apps-service/src/index.ts, packages/feedback-service/src/resolver.ts, packages/notification-spa/src/app/index/index.component.ts, packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.ts, packages/notification-spa/src/app/manage-notification/manage-notification.component.ts, packages/notifications-service/src/engine.ts
Fixed the alerts in one platform for microservices and spas which is raised as part of code review from @lgtm-bot.
No
N/A
=> (chore:alerts) - Fixed alerts for the microservices and SPAs in one platform

packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.scss, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.ts
1. Fixed broken link in lighthouse-spa homepage
2. Added documentation link
No
<details>
</details>
=> fix: fixed links of lighthouse-spa

packages/ssi-service/package-lock.json, packages/ssi-service/src/nav/nav.js
-  Fixed SSI path for SPAs 
- No
=> fix(#1032) - Link error for apps on SSI app drawer

.gitignore, packages/developer-console-spa/lighthouserc.js, packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/documentation-spa/lighthouserc.js, packages/documentation-spa/package-lock.json, packages/feedback-spa/lighthouserc.js, packages/feedback-spa/package.json, packages/home-spa/lighthouserc.js, packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/lighthouse-spa/lighthouserc.js, packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/search-spa/lighthouserc.js, packages/search-spa/package-lock.json, packages/search-spa/package.json, packages/user-group-spa/lighthouserc.js, packages/user-group-spa/package-lock.json, packages/user-group-spa/package.json, puppeteerScript.js
Configurations for the Platform SPAs for the running tests with lighthouse-ci with the puppeter scripts
No
N/A
=> (feat:1191) - Included the Configs for the lighthouse ci for One Platform

.github/workflows/build-api-gateway.yml, .github/workflows/build-apps-service.yml, .github/workflows/build-feedback-service.yml, .github/workflows/build-notifications-service.yml, .github/workflows/build-search-service.yml, .github/workflows/build-user-group-service.yml
=> feat(gh-actions): Updates github actions for the release branch

.github/workflows/build-lighthouse-service.yml, packages/lighthouse-service/Dockerfile
Included the Lighthouse Image on github images
No.
N/A
=> (feat: lh-image) Created github Image for the lighthouse service

packages/lighthouse-spa/src/app/app.component.html, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html, packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.html, packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.ts, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.scss, packages/lighthouse-spa/src/app/shared/shared.module.ts, packages/lighthouse-spa/src/styles.scss
- Fixed broken links
- UI Improvement
No
=> Hotfix: ui improvment and fixed broken link

packages/search-service/src/search-config/helpers.ts, packages/search-service/src/search-config/resolver.ts, packages/search-service/src/search-mapping/cron.ts
ONEPLAT-1304
- Implemented batching and retry for the indexing of the search data
No
<details>
</details>
=> Batching & retry the index operation for search service.

packages/lighthouse-service/Dockerfile
Included the non-root permission for the image.
No
N/A
=> (Fix:lh-image) - Included non-root permission for the image

.github/workflows/build-api-gateway.yml, .github/workflows/build-apps-service.yml, .github/workflows/build-feedback-service.yml, .github/workflows/build-lighthouse-service.yml, .github/workflows/build-notifications-service.yml, .github/workflows/build-search-service.yml, .github/workflows/build-user-group-service.yml
- Adds workflow_dispatch inputs for ghactions
- And refactors the conditions for auto generating qa and stage tags
No.
N/A
=> fix(ghactions): Adds workflow_dispatch inputs for ghactions

packages/lighthouse-service/Dockerfile
Included NPM_CONFIG_Prefix to the configuration to the image.
No
N/A
=> (fix:lh-image) - Included NPM_CONFIG_Prefix to the configuration to the image.

packages/user-group-spa/package-lock.json, packages/user-group-spa/package.json
The react packages were out of date, and had some compatibility issues with the `@patternfly/react-table`.
No.
N/A
=> fix(user-group-spa): Upgrades react and react-table package versions and fixes the build error

e2e/integration/devconsoletests.js
Write test cases for Developer console.
no
<details>
</details>
=> FEAT:ONEPLAT-1063-E2E tests: Write test cases for Developer console.

packages/user-group-spa/src/App.jsx, packages/user-group-spa/src/components/Form.jsx, packages/user-group-spa/src/components/Group.jsx, packages/user-group-spa/src/components/Home.jsx, packages/user-group-spa/src/components/NotFound.jsx, packages/user-group-spa/src/components/User.jsx, packages/user-group-spa/src/services/GroupsAPI.js
Fixed the build warning messages and removed/commented unused variables.
No.
N/A
=> fix(user-group-spa): Removes unused variables and fixes build warnings

packages/ssi-service/src/nav/nav.js
- Corrected the changed app service
- No
- N/A
=> hot-fix(ssi) - Added app path for hosted and built-in services

e2e/helper/apps.list.js, e2e/integration/devconsoletests.js, e2e/integration/feedbacktests.js
Added tests for Dev Console app settings page
No
<details>
</details>
=> FEAT- ONEPLAT-1365-E2E Test Cases - Dev Console App Settings page

packages/developer-console-spa/src/components/AddAppForm.tsx, packages/developer-console-spa/src/components/AppSettings.tsx
=> hotfix(dev-console): Fixes typos in developer console toast messages

packages/feedback-spa/src/views/Home.vue
- Added toaster notification for csvExport
- No
=> fix(#1059) - Toaster notification across entire platform

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/set-env.ts, packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.scss, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.scss, packages/lighthouse-spa/src/app/dashboard/types.d.ts, packages/lighthouse-spa/src/app/playground/components/home/home.component.html, packages/lighthouse-spa/src/app/playground/components/home/home.component.scss, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.scss, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.ts, packages/lighthouse-spa/src/index.html
1370
1. Updated ui with new changes
2. Fixed broken set-env and links of doc
No
<details>
</details>
=> feat(1370): updated ui of dashboard, cards and fixed broken links

e2e/integration/devconsoletests.js, e2e/integration/hometests.js, e2e/integration/searchtests.js, e2e/integration/ssitests.js, e2e/integration/usergrouptests.js
Dev Console Feedback tests and redesigned the existing tests.
No
<details>
</details>
=> FEAT-ONEPLAT-1363 and ONEPLAT-1425- Dev Console Feedback tests and redesigned the existing tests.

packages/api-catalog-spa/spaship.yaml, packages/developer-console-spa/spaship.yaml, packages/documentation-spa/spaship.yaml, packages/feedback-spa/spaship.yaml, packages/home-spa/spaship.yaml, packages/lighthouse-spa/spaship.yaml, packages/notification-spa/spaship.yaml, packages/search-spa/spaship.yaml, packages/user-group-spa/spaship.yaml
- Added buildDir to all SPAs
- No
N/A
=> chore(#1084) - Update SPAship config file (spaship.yml) in all SPAs to add buildDir

e2e/helper/apps.list.js, e2e/integration/lighthousetests.js
E2E Test Cases - Write test cases for Lighthouse SPA
No
<details>
</details>
=> FEAT-ONEPLAT-1362-E2E Test Cases - Write test cases for Lighthouse SPA

packages/opc-base/README.md, packages/opc-base/docs/opc-provider.md
1. Changed opc-base doc relative urls to absolute ones for npm.
2. Fixed typo in opc-provider doc
No
No
=> hotfix: changed opc-base doc redirect to absolute and fixed typo in doc

docker-compose.yml, packages/lighthouse-service/service.ts, packages/lighthouse-service/src/lighthouse-spa-config/helpers.ts, packages/lighthouse-service/src/lighthouse-spa-config/resolver.ts, packages/lighthouse-service/src/lighthouse-spa-config/schema.ts, packages/lighthouse-service/src/lighthouse-spa-config/typedef.graphql, packages/lighthouse-service/src/property-manager/resolver.ts, packages/lighthouse-service/src/types.d.ts
1462
1. Implemented lighthouse spa configuration service
2. Provided CRUD operations and all of the acceptance criteria functionalities 
No
NA
=> feat(1462): lighthouse spa configuration service

packages/opc-base/package.json
1. Changed opc-base version to `1.0-beta`
No
=> hotfix: changed opc-base pkg version to beta

packages/documentation-spa/docs/onboarding-guide/onboarding-guide.md, packages/documentation-spa/package-lock.json, packages/documentation-spa/package.json, packages/documentation-spa/sidebars.js
-  Converted docs to md format and edited the doc
- No
=> doc(#1101) -Documentation - Add new dev onboarding guide in OP home page

packages/api-catalog-service/src/e2e/api-catalog.spec.ts, packages/api-catalog-service/src/e2e/mock.json, packages/api-catalog-service/src/namespace/resolver.ts, packages/api-catalog-service/src/namespace/typedef.graphql, packages/api-catalog-service/src/shared/cron/cron.ts, packages/api-catalog-service/src/shared/emails/update-email-config.ts, packages/api-catalog-service/src/shared/helpers.ts, packages/api-catalog-service/src/types.d.ts
- Included the API Test cases
- Included schema pulling for frontend configs
- Included Subscriptions fixes for the profile
No
<details>
=> Included test cases, subscriptions and schema pulling for API Catalog

packages/opc-base/package-lock.json, packages/opc-base/package.json
1. changed opc-base version to 1.0.0-beta
No
=> hotfix: changed opc-base version to 1.0.0-beta

packages/documentation-spa/blog/2021-09-09-state-of-one-platform-aug-2021.md, packages/documentation-spa/package.json
ONEPLAT-1388
- Adds the One Platform blog update for the August-2021
No
<details>
</details>
=> Feat#1472: State of One Platform Aug blog update

packages/opc-base/package.json
1. Removed opc-base package.json private field
No
=> hotfix: removed opc-base private field in package.json

packages/opc-base/package.json
1. FIxed blocking configuration in package.json of opc-base
No
=> hotfix: fixed opc-base package.json for publishing

e2e/integration/innovationhubtests.js
Write e2e tests for Idea Hub
No
<details>
</details>
=> FEAT-ONEPLAT-1437-E2E Test Cases - Idea hub

.github/workflows/build-api-catalog-service.yml, docker-compose.yml, packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/e2e/api-catalog.spec.ts, packages/api-catalog-service/src/e2e/mock.json, packages/api-catalog-service/src/namespace/resolver.ts, packages/api-catalog-service/src/namespace/schema.ts, packages/api-catalog-service/src/namespace/typedef.graphql, packages/api-catalog-service/src/setup/database.ts, packages/api-catalog-service/src/shared/cron/cron.ts, packages/api-catalog-service/src/shared/cron/index.ts, packages/api-catalog-service/src/shared/emails/update-email-config.ts, packages/api-catalog-service/src/shared/helpers.ts, packages/api-catalog-service/src/types.d.ts
- Included the Pagination for the API
- Included the API documentation, Docker Configuration & Github Image configuration
No
<details>
</details>
=> fix:1447 Included github image configuration, docker configuration & Pagination to the API in API Catalog

packages/developer-console-spa/src/components/lighthouse/LinkProjectForm.tsx, packages/developer-console-spa/src/services/lighthouse.ts, packages/developer-console-spa/src/types.ts, packages/developer-console-spa/src/utils/gql-queries/list-lh-projects-branches.ts, packages/developer-console-spa/src/utils/gql-queries/list-lh-projects.ts
ONEPLAT-1473
- Consuming listLHproject & listLHprojectBranches query pagination changes in dev console.
No
<details>
</details>
=> Feat#1473: Consuming LHproject query changes in dev console.

packages/apps-service/src/@types/apps/index.d.ts, packages/apps-service/src/modules/apps/model.ts, packages/apps-service/src/modules/apps/resolver.ts, packages/apps-service/src/modules/apps/schema.gql.ts
Added additional fields to the App Database schema for description and permissions.
Yes.
There is a schema change for the databases field, but it shouldn't affect anything since it was not being used yet.
N/A
=> feat(apps): Add description & permissions to db

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/app/dashboard/components/property-card/property-card.component.html, packages/lighthouse-spa/src/app/dashboard/components/property-card/property-card.component.scss, packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts, packages/lighthouse-spa/src/app/dashboard/dashboard.module.ts, packages/lighthouse-spa/src/app/dashboard/dashboard.service.ts, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.scss, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.scss, packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.html, packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.scss, packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.html, packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.spec.ts, packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.ts, packages/lighthouse-spa/src/app/shared/shared.module.ts, packages/lighthouse-spa/src/styles.scss
1. UI improvements in larger screen
2. Ranking order change
3. Removed infinite scroller dependency
No
<details>
| Description | Screenshot |
| - | - |
| Homepage/Project list page | <img width="1436" alt="Screenshot 2021-09-28 at 3 16 57 PM" src="https://user-images.githubusercontent.com/31166322/135066629-f09d317b-7cdb-41ef-8353-8621c0ec91ae.png"> |
| Score page | <img width="1436" alt="Screenshot 2021-09-28 at 3 17 12 PM" src="https://user-images.githubusercontent.com/31166322/135066755-13f3584a-6d1a-45b8-b2bc-df5f650cec8e.png"> |
| Scorepage with branch select open | <img width="1436" alt="Screenshot 2021-09-28 at 3 17 19 PM" src="https://user-images.githubusercontent.com/31166322/135066853-2ec1315c-12ca-469f-9e1e-2cdd7a4598e3.png"> |
| Leaderboard …
=> feat: ui improvements to lh spa on larger screen and ranking change

packages/developer-console-spa/.env.example, packages/developer-console-spa/package-lock.json, packages/developer-console-spa/src/App.tsx, packages/developer-console-spa/src/assets/storage_black_24dp.svg, packages/developer-console-spa/src/components/AppIndex.css, packages/developer-console-spa/src/components/AppOverview.tsx, packages/developer-console-spa/src/components/ConfigureCouchDB.tsx, packages/developer-console-spa/src/components/ConfigureLighthouse.tsx, packages/developer-console-spa/src/components/Sidebar.tsx, packages/developer-console-spa/src/components/couchdb/CreateDBForm.tsx, packages/developer-console-spa/src/types.ts, packages/developer-console-spa/src/utils/gql-queries/app-by-appid.ts, packages/developer-console-spa/src/utils/gql-queries/create-app-database.ts, packages/developer-console-spa/src/utils/gql-queries/index.ts
ONEPLAT-1319
This PR contains changes related to the CouchDB config implementation in Developer Console SPA:
- Create DB instance form
- Listing DB instances
- Search for the DB instances
No
<details>
1. Landing page:
2. Create DB form: 
3. DatabaseList:
4. Search for DB:
5. Blank Search Results:
</details>
=> Feat#1319: CouchDB config implementation in Developer Console SPA

packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/feedback-service/src/helpers.ts, packages/feedback-service/src/resolver.ts
Corrected email template user query for the feedback microservice
No
<details>
</details>
=> fix:#1462 - updated email template & user query

packages/search-spa/src/app/search/search.component.html
Patches https://github.com/1-Platform/one-platform/security/code-scanning?query=tag%3Aexternal%2Fcwe%2Fcwe-1022+tool%3ACodeQL
No
=> fix(cwe-1022): patches unsafe external link

packages/feedback-service/src/resolver.ts
As the [deepsource analysis tool says](https://deepsource.io/gh/1-Platform/one-platform/issue/JS-D008/occurrences?page=1), the [`Array.prototype.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) function is used wrongly here[^1], I think that [`Array.prototype.forEach()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) function is more convenient[^2] here.
[^1]: Because this function is used to apply a change to the elements of Array (one by one) and return the altered Array. In this code, the [`Array.prototype.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) is returning `undefined` implicitly, and the returned array with this transformation …
=> Replaces use of map with forEach instead

e2e/integration/dsaltests.js
=> FEAT-ONEPLAT-1438- e2e tests for dsal reservation module

e2e/integration/dsaltests.js
…  button in the modal box
Able to click on the confirm button that is displayed in the modal box
No
<details>
</details>
=> test(#1438) :Modifying the E2E DSAL TC to include click on the confirm button inside the modal

packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/namespace/resolver.ts, packages/api-catalog-service/src/namespace/schema.ts, packages/api-catalog-service/src/namespace/typedef.graphql, packages/api-catalog-service/src/shared/cron/cron.ts, packages/api-catalog-service/src/shared/emails/update-email-config.ts, packages/api-catalog-service/src/shared/helpers.ts, packages/api-catalog-service/src/shared/typedef.graphql, packages/api-catalog-service/src/types.d.ts
Closes 1284
1. Improved queries with new filters and search
2. Add new subscription status mutation
3. Added new query to get count of various apis
Yes
<details>
</details>
=> feat(1284): api-catalog-service improvements with the new

packages/user-group-service/src/users/typedef.graphql
NA
- Removing duplicate `membershipInfo` field from the GroupType
<details>
</details>
=> hotfix: Removing membershipInfo duplicate field from group type.

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html, packages/lighthouse-spa/src/app/dashboard/pipes/timeline-score-formater.pipe.ts, packages/lighthouse-spa/src/app/dashboard/types.d.ts, packages/lighthouse-spa/src/app/graphql.module.ts, packages/lighthouse-spa/src/app/playground/components/home/home.component.html, packages/lighthouse-spa/src/app/playground/components/home/home.component.spec.ts, packages/lighthouse-spa/src/app/playground/components/home/home.component.ts, packages/lighthouse-spa/src/app/playground/playground.gql.ts, packages/lighthouse-spa/src/app/playground/playground.module.ts, packages/lighthouse-spa/src/app/playground/playground.service.ts, packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.html, packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.spec.ts, packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.ts, packages/lighthouse-spa/src/app/shared/shared.module.ts
1611, 1616
1. Fixed loader showing in empty branches project detail page
2. Fixed audit upload button disabled
3. Implemented proper validation for audit upload form
No
<details>
</details>
=> fix(1611,1616): Lighthouse - fixed loader on empty branches and  audit upload fix 

packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/components/couchdb/AddUserForm.tsx, packages/developer-console-spa/src/components/couchdb/CreateDBForm.tsx, packages/developer-console-spa/src/components/lighthouse/CreateProjectForm.tsx
ONEPLAT-1610
- Validates and shows messages when only white spaces are entered in the field.
No
<details>
</details>
=> Fix#1610: Adding validations for only white spaces in the fields.

packages/apps-service/package-lock.json, packages/apps-service/package.json, packages/apps-service/src/modules/apps/index.ts, packages/apps-service/src/modules/apps/model.ts, packages/apps-service/src/modules/microservices/index.ts, packages/apps-service/src/modules/microservices/model.ts, packages/apps-service/src/modules/microservices/resolver.ts
Fixed the imports and updated the static method for the schema structure
No
N/A
=> Fixed the imports and updated the static method for the schema structure

packages/api-catalog-spa/public/index.html, packages/component-catalog-spa/public/index.html, packages/developer-console-spa/public/index.html, packages/feedback-spa/public/index.html, packages/home-spa/src/_includes/layout/base.njk, packages/home-spa/src/_includes/partials/footer.njk, packages/home-spa/src/_includes/partials/header.njk, packages/lighthouse-spa/src/index.html, packages/search-spa/src/index.html, packages/user-group-spa/public/index.html
1554
1. Applied source integrity to all third party scripts and style sheet
2. Updated and locked all latest scripts of op components
No
<details>
</details>
=> feat(1554): applied source integrity to all third party scripts

packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/components/couchdb/UsersTable.tsx
NA
- Fixing the Dev Console SPA build issue in the deployment pipeline.
No
<details>
</details>
=> hotfix: Fixed build issue in Jenkins deployment pipeline.

packages/apps-service/Dockerfile, packages/apps-service/package-lock.json, packages/apps-service/package.json, packages/apps-service/src/@types/apps/index.d.ts, packages/apps-service/src/index.ts, packages/apps-service/src/lib/logger.ts, packages/apps-service/src/modules/apps/model.ts, packages/apps-service/src/modules/apps/resolver.ts, packages/apps-service/src/modules/apps/schema.gql.ts, packages/apps-service/src/services/couchdb.ts, packages/apps-service/src/services/user-group.ts, packages/apps-service/src/setup/database.ts, packages/apps-service/src/utils/apps-helper.ts, packages/apps-service/src/utils/gql-queries/getUser.ts, packages/apps-service/src/utils/unique-id-from-path.ts
- Created mutation for `transferAppOwnership` for apps in apps service
- And refactored the apps schema
No.
N/A
=> feat(apps): Create mutation for transfer ownership

packages/developer-console-spa/src/components/couchdb/UpdateCouchDBConfig.tsx, packages/developer-console-spa/src/components/couchdb/UsersTable.tsx
ONEPLAT-1601
- Implemented the delete user permissions for the database.
No
<details>
Delete confirmation:
Delete success message:
</details>
=> Feat(#1601): Implemented delete user permissions for database.

e2e/integration/apicatalogtests.js
Added TC for add api catalog test 
No
<details>
</details>
- Yes
=> add api catalog test #test(ONEPLAT-1698)

e2e/integration/apicatalogtests.js, e2e/integration/devconsoletests.js, e2e/integration/feedbacktests.js, e2e/integration/lighthousetests.js, e2e/integration/usergrouptests.js
=> Made corrections for failing tests (ONEPLAT-1702)

e2e/integration/apicatalogtests.js, e2e/integration/devconsoletests.js, e2e/integration/lighthousetests.js, e2e/integration/searchtests.js
Jenkins failing test fixes
<details>
</details>
- Yes
=> modifications in existing test test(ONEPLAT-1702)

packages/feedback-service/.env.example, packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/feedback-service/src/helpers.ts, packages/feedback-service/src/resolver.ts
Updated the JIRA integration with token-based system
No
N/A
=> (feat:1705) - Updated the Auth to Access tokens for Jira Integrations

e2e/integration/ssitests.js
=> changed ssi tests ONEPLAT-1709

packages/lighthouse-spa/set-env.ts, packages/lighthouse-spa/src/environments/environment.prod.ts, packages/lighthouse-spa/src/environments/environment.ts, packages/search-spa/set-env.ts, packages/search-spa/src/environments/environment.prod.ts, packages/search-spa/src/environments/environment.ts
1. Fixed sentry dsn as `"undefined"` on not giving env
No
<details>
</details>
=> hotfix: fixed angular spa env sentry dsn as string undefined

packages/reverse-proxy-service/package-lock.json, packages/reverse-proxy-service/package.json, packages/reverse-proxy-service/src/app.ts, packages/reverse-proxy-service/src/no-cors-proxy/index.ts, packages/reverse-proxy-service/src/no-cors-proxy/resolver.ts
1. Implemented no-cors proxy in reverse proxy for api catalog
No
<details>
</details>
=> feat: reverse-proxy implemented no-cors proxy for api catalog

packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/namespace/typedef.graphql, packages/api-catalog-service/src/shared/helpers.ts, packages/api-catalog-service/src/shared/typedef.graphql, packages/api-catalog-service/src/types.d.ts
Api Catalog type conflict with user group service
No
N/A
=> hotfix: Fixed the typeconflicts in api catalog with user-group service

packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/namespace/schema.ts, packages/api-catalog-service/src/shared/cron/cron.ts, packages/api-catalog-service/src/shared/cron/index.ts, packages/api-catalog-service/src/shared/emails/update-email-config.ts, packages/api-catalog-service/src/shared/helpers.ts
Updated the email template for API Catalog
No
N/A
=> chore: Updated the email template for API Catalog

e2e/integration/apicatalogtests.js, e2e/integration/feedbacktests.js, e2e/integration/searchtests.js, package.json
=> test for search,edit and delete of apis(ONEPLAT-1724)

cypress.json, e2e/integration/apicatalogtests.js, package.json
=> apicatalog test and chromium browser test (ONEPLAT-1702)

packages/component-catalog-spa/package-lock.json, packages/component-catalog-spa/src/Components/Main.jsx, packages/component-catalog-spa/src/Configs/component-libraries.js
- Changed the link for webrh components 
- No
=> fix(ONEPLAT/1735): Changed the link for webrh components

e2e/integration/searchtests.js
Resolved the failing test of search spa
No
<details>
</details>
=> search test  fixes (ONEPLAT-1707)

packages/search-spa/package-lock.json, packages/search-spa/package.json
1. Migrated search spa  opc-nav to latest one
No
<details>
</details>
=> hotfix: search-spa migrated opc-nav to latest

packages/documentation-spa/docusaurus.config.js, packages/documentation-spa/package-lock.json, packages/documentation-spa/package.json
- 1739
1. Fixed broken link in doc spa footer
No
<details>
</details>
=> fix(1739): doc-spa - fixed broken links in footer

packages/api-catalog-service/Dockerfile, packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/e2e/api-catalog.spec.ts, packages/api-catalog-service/src/e2e/mock.js
Updated the test cases for the API catalog microservice.
No
<details>
</details>
=> chore:1677 - Updated the test cases for the api-catalog microservice

packages/user-group-spa/package-lock.json, packages/user-group-spa/package.json, packages/user-group-spa/public/mockServiceWorker.js, packages/user-group-spa/src/App.test.js, packages/user-group-spa/src/components/Form.test.js, packages/user-group-spa/src/components/Group.test.js, packages/user-group-spa/src/components/Home.test.js, packages/user-group-spa/src/components/NotFound.test.js, packages/user-group-spa/src/components/User.test.js, packages/user-group-spa/src/mocks/browser.js, packages/user-group-spa/src/mocks/data.js, packages/user-group-spa/src/mocks/handlers.js, packages/user-group-spa/src/mocks/server.js, packages/user-group-spa/src/setupTests.js
ONEPLAT-1685
- Unit test cases for User groups SPA
No
<details>
</details>
=> Feat#1685: Unit test cases for User groups SPA

packages/reverse-proxy-service/.env.example, packages/reverse-proxy-service/README.md, packages/reverse-proxy-service/package-lock.json, packages/reverse-proxy-service/package.json, packages/reverse-proxy-service/src/app.ts, packages/reverse-proxy-service/src/config/env.ts, packages/reverse-proxy-service/src/couchdb/resolver.ts, packages/reverse-proxy-service/src/middleware/jwtAuth.ts, packages/reverse-proxy-service/src/restricted-spas/index.ts, packages/reverse-proxy-service/src/restricted-spas/resolver.ts, packages/reverse-proxy-service/src/spec/restricted-spas.spec.ts, packages/reverse-proxy-service/src/utils/keycloakAuth.ts
Added keycloak middleware for SSO auth at the gateway level for some restricted SPAs.
No.
N/A
=> feat(rproxy): Add keycloak middleware for SPAs

packages/search-service/package-lock.json, packages/search-service/package.json, packages/search-service/src/e2e/mock.js, packages/search-service/src/e2e/mock.json, packages/search-service/src/e2e/search.spec.ts
Updated the test cases with respective to new APIs
No
<details>
</details>
=> (chore:1680) - Updated the test cases for the Search Microservice

packages/opc-base/package-lock.json, packages/opc-base/package.json, packages/opc-base/src/config/graphql.ts, packages/opc-base/src/opc-provider/opc-provider.ts
1. Due to min timeout websocket was getting closed early
2. Removed isSearchable in menu drawer links attribute
No
<details>
</details>
=> fix: fixed early websocket closing and api changed to new menu-drawer

packages/search-spa/src/app/search/search.component.html, packages/search-spa/src/app/search/search.component.ts
- 1779
1. Implemented search spa dropdown onblur on filters
No
<details>
https://user-images.githubusercontent.com/31166322/148246815-d400f991-8f90-4246-b340-9ebcd4398873.mov
</details>
=> fix(1779) - search-spa fixed dropdown onblur closing

packages/opc-base/package-lock.json, packages/opc-base/package.json, packages/opc-base/src/gql/opc-app-layout.ts
Removed the unused parameter in the opc-base API querys
No
N/A
=> 1577 - Updated the querys in the opc-base package

packages/user-group-service/package-lock.json, packages/user-group-service/package.json, packages/user-group-service/src/e2e/mock.js, packages/user-group-service/src/e2e/mock.json, packages/user-group-service/src/e2e/rover.mock.js, packages/user-group-service/src/e2e/user.spec.ts
As part of ONEPLAT-1686 & Closing #1369
- Written unit test cases for user-groups service
<details>
</details>
=> Feat#1686: User-group service unit tests, covered users and user group tests

packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/@types/Feedback/types.d.ts, packages/developer-console-spa/src/components/ConfigureFeedback.tsx, packages/developer-console-spa/src/hooks/useFeedbackConfig.ts, packages/developer-console-spa/src/services/feedbackConfig.ts, packages/developer-console-spa/src/utils/formErrorMsg.ts, packages/developer-console-spa/src/utils/gql-queries/app-feedback-config.ts, packages/developer-console-spa/src/utils/gql-queries/create-feedback-config.ts, packages/developer-console-spa/src/utils/gql-queries/index.ts, packages/developer-console-spa/src/utils/gql-queries/update-feedback-config.ts
- 1577
1. Updated dev console feedback page with the server changes
2. Migrated to react-hook-form for feedback page
No
<details>
</details>
=> feat(1577): updated dev console feedback page with server

packages/feedback-spa/src/components/ListFeedback.vue, packages/feedback-spa/src/graphql/gqlQueries.js, packages/feedback-spa/src/views/Home.vue, packages/feedback-spa/tests/unit/ListFeedback.spec.js
Updated the feedback spa with the queries and with changes.
No
N/A
=> 1577 - Updated the feedback SPA with the queries

.gitignore, cypress/support/commands.js, cypress/support/index.js, e2e/integration/apicatalogtests.js, e2e/integration/ideahubtests.js, e2e/integration/searchtests.js, e2e/integration/usergrouptests.js, package-lock.json, package.json
fix for failing tests in jenkins and xpath support in cypress
fix for failing tests in jenkins and xpath support in cypress
<details>
</details>
=> test(idea,usergroup,search):fix for failing tests in jenkins and xpath support in cypress

.github/PULL_REQUEST_TEMPLATE.md
NA
- Fixed typos in PR template
<details>
</details>
=> Fix: Typo in Pull Request template

packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/feedback-service/src/feedbacks/helpers.ts
1. Fixed module value null in feedback service due to immutability from mongoose doc
2. Changed feedback frontend url in indexing
No
<details>
</details>
=> hotfix: feedback-service module null fixed

packages/api-catalog-service/.env.example, packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/namespace/resolver.ts, packages/api-catalog-service/src/namespace/typedef.graphql, packages/api-catalog-service/src/setup/env.ts
Integrated the EXD Catalog with the API catalog
No
`
<details>
</details>
=> feat:1811 - Integrated the EXD Catalog with the API catalog

packages/feedback-spa/index.html, packages/feedback-spa/package-lock.json, packages/feedback-spa/package.json, packages/feedback-spa/src/main.tsx, packages/feedback-spa/src/pages/HomePage/HomePage.tsx
1. Resolves css issue in production
ViteJS uses css code splitting to chunk css into multiple modules to load css only when needed. This causes reset css to be imported after vendor css.
The base css of pfe contains all css variables and also a particular css rule on button and input that takes priority when imported after the vendor pfe css, causing all the variables to be useless on padding, margin etc.
To avoid this, pfe base is imported from unpkg and kept at top.
2. Changed jsonexport importing
No
<details>
</details>
=> hotfix: feedback spa fixed pf import issue in build

.gitignore, cypress.json, cypress/plugins/index.js, cypress/support/index.js, e2e/integration/lighthousetests.js, e2e/integration/usergrouptests.js, e2e/summarize.js, package-lock.json, package.json
…led tests cases
Adding screenshots as part of report for failed test
No
<details>
</details>
=> test(screenshotfeature): Adding screenshots as part of report for failed test

packages/feedback-spa/.eslintrc.js, packages/feedback-spa/package-lock.json, packages/feedback-spa/package.json, packages/feedback-spa/src/components/ReadMore/ReadMore.tsx, packages/feedback-spa/src/components/ReadMore/index.tsx, packages/feedback-spa/src/pages/HomePage/HomePage.tsx, packages/feedback-spa/src/pages/HomePage/components/FeedbackCard/FeedbackCard.tsx, packages/feedback-spa/src/pages/HomePage/components/FeedbackCard/feedbackCard.test.tsx, packages/feedback-spa/src/pages/HomePage/components/FeedbackDetailCard/FeedbackDetailCard.tsx, packages/feedback-spa/src/pages/HomePage/components/FeedbackDetailCard/feedbackDetailCard.test.tsx
1. Error chip missing in feedback list
2. Added view more when summary or description is too big in feedback
3. Updated testcases
4. Fixed validations for the export button
No
<details>
</details>
=> fix: feedback-spa - fixed error chip missing in feedback list

cypress.json, e2e/integration/devconsoletests.js, e2e/integration/feedbacktests.js
… and modified dev console failing test for feedback spa
test(feedbackanddevconsole):added new test cases for new feedback spa and modified devconsole failing tests for feedback module
No
<details>
</details>
=> test(feedbackanddevconsole):added new test cases for new feedback spa and modified devconsole failing tests for feedback module

packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/feedback-service/src/feedbacks/resolver.ts
1. Fixed status filter not working
No
<details>
</details>
=> hotfix(feedback-service): fixed status filter not working

packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
1. Added feedback spa link to feedback list page in dev console
2. Truncated summary in table to 200 characters
3. Added color change for bug in list view
No
<details>
</details>
=> feat(dev-console): added feedback spa link in feedback list page

packages/user-group-spa/package-lock.json, packages/user-group-spa/src/components/User.jsx
> Fixes ONEPLAT-1829
Fixes the broken "Groups" field in the "My Profile" page.
No. 
<details>
</details>
=> fix(user-spa): Fix for groups in user profile

cypress.json, e2e/integration/devconsoletests.js, e2e/integration/feedbacktests.js, e2e/integration/lighthousetests.js, e2e/integration/searchtests.js, e2e/integration/ssitests.js, e2e/integration/usergrouptests.js
…atures
changes done in search,ssi,usergroup spa to support new features (ui changes)
changes done in search,ssi,usergroup spa to support new features (ui changes)
<details>
</details>
=> test(e2e): changes done in search,ssi,usergroup spa to support new features (ui changes)

e2e/integration/apicatalogtests.js
test(apicatalog):added timeouts to wait for an element
No
<details>
</details>
=> test(apicatalog):added timeouts to wait for an element

packages/developer-console-spa/src/components/ConfigureDatabase.tsx
Refactored `url`reassignment inside useCallback
No.
N/A
=> hotfix(dev-console): fix var reassignment

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/pages/ApiCUDPage/ApiCUDPage.tsx, packages/api-catalog-spa/src/pages/ApiCUDPage/hooks/useGetANamespace.tsx, packages/api-catalog-spa/src/pages/ApiDescriptionPage/ApiDescriptionPage.tsx, packages/api-catalog-spa/src/pages/ApiDescriptionPage/hooks/useGetANamespace.tsx, packages/api-catalog-spa/src/pages/GqlPlaygroundPage/GqlPlaygroundPage.tsx, packages/api-catalog-spa/src/pages/GqlPlaygroundPage/hooks/useGetANamespace.tsx, packages/api-catalog-spa/src/pages/SwaggerToolPage/SwaggerToolPage.tsx, packages/api-catalog-spa/src/pages/SwaggerToolPage/hooks/useGetANamespace.tsx, packages/api-catalog-spa/src/pages/VoyagerToolPage/VoyagerToolPage.tsx, packages/api-catalog-spa/src/pages/VoyagerToolPage/hooks/useGetANamespace.tsx
1. 1865
1. Changed reverse proxy no-cors proxy url format change
2. Fixed type errors caused by renovate bot changes
No
<details>
</details>
=> feat(1865): api-catalog-spa - changed no-cors url format and fixed type error

packages/reverse-proxy-service/package-lock.json, packages/reverse-proxy-service/package.json, packages/reverse-proxy-service/src/couchdb/index.ts, packages/reverse-proxy-service/src/no-cors-proxy/index.ts, packages/reverse-proxy-service/src/no-cors-proxy/resolver.ts
1. FIxed url issue in reverese proxy no cors proxy for api catalog
2. Change couchdb with url
No
<details>
</details>
=> fix(reverse-proxy): fixed no-cors-proxy url issue

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts, packages/lighthouse-spa/src/app/dashboard/dashboard.service.spec.ts, packages/lighthouse-spa/src/app/dashboard/dashboard.service.ts, packages/lighthouse-spa/src/app/dashboard/mock-dashboard.ts, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html, packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.spec.ts, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts, packages/lighthouse-spa/src/app/leaderboard/leaderboard.gql.ts, packages/lighthouse-spa/src/app/leaderboard/mock-leaderboard.ts, packages/lighthouse-spa/src/app/leaderboard/types.d.ts, packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
1. 1873
1. Updated leaderboard query changes
2. Fixed bug in coloring 
3. Updated text cases
No
<details>
</details>
=> feat(1873): lighthouse-spa : updated leaderboards with query change

packages/developer-console-spa/src/components/Sidebar.css
UI Issue
- Fixes UI issue related to positioning and patternfly css override
No.
<details>
</details>
=> hotfix(dev-console): Add scope to sidebar css rules

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/index.tsx, packages/component-catalog-spa/package-lock.json, packages/component-catalog-spa/package.json, packages/component-catalog-spa/src/index.jsx, packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/index.tsx, packages/documentation-spa/package-lock.json, packages/documentation-spa/package.json, packages/documentation-spa/src/theme/Layout/index.jsx, packages/feedback-spa/package-lock.json, packages/feedback-spa/package.json, packages/feedback-spa/src/main.tsx, packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/_includes/partials/header.njk, packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/main.ts, packages/search-spa/package-lock.json, packages/search-spa/package.json, packages/search-spa/src/main.ts, packages/user-group-spa/package-lock.json, packages/user-group-spa/package.json, packages/user-group-spa/src/index.js
1. 1872
1. Updated sentry release name to op prefix one
2. Updated all sentry packages to latest version
No
<details>
</details>
=> chore(1872): updated all sentry release name and updated sentry to latest version

cypress.json
enablement of the json report to generate for the email summary
<details>
</details>
=> test(e2e): enabling the json report for the email summary

e2e/integration/devconsoletests.js, e2e/summarize.js
fix devconsole locators and changed report file name for email summary
<details>
</details>
=> test(e2e):fix devconsole locators and changed report file name for email summary

cypress/support/index.js, e2e/integration/apicatalogtests.js, e2e/integration/devconsoletests.js, e2e/integration/feedbacktests.js, e2e/integration/lighthousetests.js, e2e/integration/searchtests.js, e2e/integration/ssitests.js, e2e/integration/usergrouptests.js, e2e/summarize.js
:removed redundant code
<details>
</details>
=> test(e2e):removed redundant test code as it is being handled in index.js

cypress.json, cypress/plugins/index.js, e2e/summarize.js, package-lock.json, package.json
…  not created
test(e2e): enabling inline assets feature so that new asset folder is not created for fix for email summary 
<details>
</details>
=> test(e2e): enabling inline assets feature so that new asset folder is not created for fix for email summary 

packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
1. Removed comment in lighthouse analytics page
No
<details>
</details>
=> chore(lighthouse-spa): removed comment from analytics html

cypress.json, e2e/integration/homepagetests.js, e2e/integration/searchtests.js
test(e2e): added home spa page static tests 
- No
=> test(e2e): added home spa page static tests

packages/apps-service/Dockerfile, packages/apps-service/package.json
Slow start in docker environment
- Updated the docker runtime command to use the node with compiled code instead of ts-node with typescript.
- Also updated npm script for dev and docker environments
No.
N/A
=> hotfix(apps): Update docker runtime command

packages/reverse-proxy-service/src/restricted-spas/index.ts
Updated the app URL of rhel developers guide
No
N/A
=> 1925 - Updated the path of rhel developers guide app

cypress.json, e2e/integration/apicatalogtests.js, e2e/integration/devconsoletests.js, e2e/integration/feedbacktests.js, e2e/integration/homepagetests.js, e2e/integration/lighthousetests.js, e2e/integration/searchtests.js, e2e/integration/ssitests.js, e2e/integration/usergrouptests.js, e2e/summarize.js, package-lock.json
added sort test for lighthouse leaderboard total column and removal of unnecessary timeouts from individual command
test(e2e): added sort test for lighthouse leaderboard total column and removal of unnecessary timeouts from individual command
No
-Yes (it is not one feature, feature addition plus some code cleaning is included
-  Yes , the test added is passing
-  Not applicable
- Not applicable
=> test(e2e): added sort test for lighthouse leaderboard total column and removal of unnecessary timeouts from individual command

packages/opc-base/package-lock.json, packages/opc-base/package.json, packages/opc-base/src/components/opc-toast/opc-toast.ts
1. 1868
1. Fixed ssi link based toast showing a tag 
No
<details>
</details>
=> fix(1868): opc-base fixed link notification

packages/home-spa/.eleventy.js
- Added copy of .htaccess in 11ty config 
- No
=> fix(1491) - HOT-FIX - .htaccess fix for home-spa 

packages/user-group-spa/package-lock.json, packages/user-group-spa/package.json, packages/user-group-spa/public/index.html
1. 1868
1. Fixed rendering of html tag inside the toast on notifications
No
<details>
</details>
=> fix(1868): user-group spa fixed link tag in toast

packages/apps-service/Dockerfile, packages/apps-service/package-lock.json, packages/apps-service/package.json
Node and npm upgrade for the apps service.
No.
N/A
=> chore(apps-service): upgrade node to v16

e2e/integration/feedbacktests.js
test(e2e):added assertions for checking bug and feedback image getting loaded 
test(e2e):added assertions for checking bug and feedback image getting loaded
=> test(e2e):added test for checking bug and feedback image getting loaded in feedback spa

packages/api-catalog-spa/package-lock.json
1. Broken build in linux machine due to package-lock issue
No
<details>
</details>
=> chore: api-catalog-spa linux compatible lock file

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/App.tsx, packages/api-catalog-spa/src/router/Router.tsx
1. Blank screen on deployment
No
<details>
</details>
=> fix(api-catalog-spa): homepage url makes screen blank

packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/App.test.tsx
1. FIxed failed test cases in api catalog spa
No
<details>
</details>
=> fix(api-catalog-spa): fixed failing test in api catalog spa

packages/reverse-proxy-service/src/restricted-spas/index.ts
Permanent redirect for an old route
No
N/A
=> feat(rproxy): redirect for rhel-developer-guide

packages/lighthouse-service/package-lock.json, packages/lighthouse-service/package.json, packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts, packages/lighthouse-service/src/lighthouse-spa-config/helpers.ts, packages/lighthouse-service/src/lighthouse-spa-config/resolver.ts, packages/lighthouse-service/src/lighthouse-spa-config/typedef.graphql
1. 1988
2. 1982
1. Changed leaderboard to floating numbers for better precision
2. Added query to fetch latest score of an app by appId
No
<details>
</details>
=> feat(1988): lighthouse-service changed leaderboard to float for better precision

e2e/integration/homepagetests.js, e2e/integration/ssitests.js, e2e/pageObject/Footer.js, e2e/pageObject/HomePage.js, e2e/pageObject/Sidebar.js
… the sidebar
test(e2e): added test scripts for checking footer links and search in sidebar
test(e2e): added test scripts for checking footer links and search in sidebar
no
no
=> test(e2e): added test scripts for checking footer links and search in sidebar

packages/component-catalog-spa/package-lock.json, packages/component-catalog-spa/package.json, packages/component-catalog-spa/src/Components/Navbar.jsx, packages/component-catalog-spa/src/Configs/footer.js
- Fixed test cases and added correct link
- No
=> fix(1524) - Update the One Platform Source Link to point to correct url on Source

e2e/integration/devconsoletests.js
test(e2e): lighthouse config page test scenarios(create project,delete project)
No
<details>
</details>
=> test(e2e): lighthouse config page test scenarios(create project,delete project)

packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/components/ConfigureLighthouse.tsx, packages/developer-console-spa/src/components/lighthouse/LinkProjectForm.tsx
1. Changed dev console lighthouse config page from app.id to appId
no
<details>
</details>
=> fix(dev-console): changed lighthouse config page using app.id to appId

docker-compose.yml, packages/search-service/package-lock.json, packages/search-service/package.json, packages/search-service/service.ts, packages/search-service/src/search-mapping/resolver.ts, packages/search-service/src/search-mapping/typedef.graphql, packages/search-service/src/search-mapping/types.d.ts
> Related to #1531 
Changed some Search Map query and mutations
Yes. Schema changes to the search map queries and mutations, but shouldn't affect anything else.
N/A
=> feat(search-service): search map schema changes

cypress.json, cypress/support/index.js, e2e/integration/usergrouptests.js, package-lock.json, package.json
test(e2e): User group SPA additional test cases(invalid search,notification message, breadcrumb,documentation link redirection)
No
<details>
</details>
=> test(e2e): User group SPA additional test cases(invalid search,notification message, breadcrumb,documentation link redirection)

e2e/integration/searchtests.js
…performing search
test(e2e): check for not found image,send feedback link and time taken for search visibility test
No
<details>
</details>
=> test(e2e): check for not found image,send feedback link and time taken for search visibility test

e2e/helper/apps.list.js, e2e/integration/devconsoletests.js
Developer Console Search and Op-Navbar tests
No
<details>
</details>
=> test(e2e): Developer Console Search and Op-Navbar tests

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/_data/footer.json, packages/home-spa/src/_includes/partials/service.njk, packages/home-spa/src/contact-us.njk
- Resolves #1542 
-  Changed emails and links for home and contact-us page in home-spa
- No
<details>
</details>
=> home-spa - chore(1542) - Home SPA - update Contact us, Source page and Blog links

cypress.json, e2e/integration/homepagetests.js, e2e/pageObject/HomePage.js
Test(e2e): additional test case scenarios for home spa(verify app link redirections, learn more link redirection)
No
<details>
</details>
=> Test(e2e): additional test case scenarios for home spa(verify app link redirections, learn more link redirection)

docker-compose.yml, packages/api-gateway-service/package-lock.json, packages/api-gateway-service/service.ts, packages/api-gateway-service/src/remote-schema.ts
Passing extra user related fields from API Gateway to the microservices, for Authorization use.
No.
N/A
=> feat(api-gateway): fwd extra fields to services

packages/home-spa/src/404.njk
- Removed extra / from path in 404
=> hot-fix(home-spa) - Hot-fix for home-spa 404 page

e2e/integration/errorpagetests.js
test(e2e): added the automation tests for error page
<details>
</details>
=> test(e2e): added the automation tests for error page

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
1. 2102
1. Changed lighthouse spa homepage card titles to lowercase
No
<details>
</details>
=> fix(2102): lh-spa - changed homepage cards title to lowercase

packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/app.ts, packages/api-catalog-service/src/index.ts
1. Changed default host parameter to server listen
2. Removed listen logger message
No
<details>
</details>
=> fix(api-catalog): added default host parameter to server

packages/lighthouse-service/package-lock.json, packages/lighthouse-service/package.json, packages/lighthouse-service/src/audit-manager/typedef.graphql, packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts, packages/lighthouse-service/src/lighthouse-db-manager/types.ts
1. 1883
1. Implemented categories to be selected when scoring from overall in lh leaderboard
No
<details>
</details>
=> feat(1883): lighthouse-service - added fields to be picked in total scoring

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/pages/APICUDPage/components/APIReview/APIReview.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/APIDescriptionPage.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/components/DetailsSection/DetailsSection.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useGetANamespaceBySlug.ts, packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useSubscribeSchema.tsx, packages/api-catalog-spa/src/utils/hasUserApiEditAccess.ts
1. Made the edit button hidden if user not the owner or created by
No
<details>
</details>
=> feat(api-catalog-spa): hiding edit button if user is not owner or created by

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
1. Fixed leader board breaking in build timeline chart
No
<details>
</details>
=> fix(lh-spa): fixed undefined error in leaderboard column function in build timeline chart

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/pages/APIDescriptionPage/APIDescriptionPage.tsx
1. 2130
1. API schema section showing namespace description bug fix
No
<details>
</details>
=> fix(api-catalog-spa): fixed schema desc showing namespace desc

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/_data/footer.json, packages/home-spa/src/_data/pageText.json
=> Chore(home-spa-test) - Changed home-spa stats

packages/lighthouse-spa/set-env.ts, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html, packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.ts, packages/lighthouse-spa/src/environments/environment.prod.ts, packages/lighthouse-spa/src/environments/environment.ts
1. 2086
1. Added env variable for doc URL to add on boarding guide
No
<details>
</details>
=> feat(2086): lh-spa - added lh doc url on getting started

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/api/types.ts, packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.helpers.ts, packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.tsx, packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.types.ts, packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APIReview/APIReview.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/APISchemaForm.tsx, packages/api-catalog-spa/src/pages/APICUDPage/hooks/index.tsx, packages/api-catalog-spa/src/pages/APICUDPage/hooks/useGetANamespaceBySlug.tsx, packages/api-catalog-spa/src/pages/APICUDPage/hooks/useGetOutages.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/APIDescriptionPage.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/apiDescriptionPage.module.scss, packages/api-catalog-spa/src/pages/APIDescriptionPage/components/ApiEnvironmentSection/ApiEnvironmentSection.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/components/DetailsSection/DetailsSection.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useGetANamespaceBySlug.ts, packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useSubscribeSchema.tsx, packages/api-catalog-spa/src/pages/HomePage/homePage.module.scss, packages/api-catalog-spa/src/utils/hasUserApiEditAccess.ts
1. 2114
2. 2076
3. 2141
1. Added cmdb code support
2. Added red hat status  outage support
3. Added invalid state for env when cron fails
4. Fixed subscription notification message
No
<details>
</details>
=> feat(2114,2076): api-catalog-spa implemented cmdb and outage integration

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/APISchemaForm.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/components/EnvironmentFormSection/EnvironmentFormSection.tsx
1. 2155
2. 2173
3. 2131
1. Fixed validation message not going away for some field change
2. Notification on successful validation of schema
3. Invalid mailing list message
No
<details>
</details>
=> fix(2155,2173,2131): fixed api catalog spa schema form bugs

package-lock.json, package.json
- Removed SPASHIP CLI as there was no requirement of the package to be installed locally
- No
- N/A
=> chore(1581) - Update SPAship cli version to latest or remove it from top level package.json

packages/lighthouse-service/package-lock.json, packages/lighthouse-service/package.json, packages/lighthouse-service/src/e2e/lighthouse.spec.ts, packages/lighthouse-service/src/e2e/mock.json, packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts, packages/lighthouse-service/src/lighthouse-spa-config/resolver.ts, packages/lighthouse-service/src/lighthouse-spa-config/typedef.graphql
Implemented the Data Export APIs for Lighthouse Service
No
N/A
=> #2147 - Implemented the Data Export APIs for Lighthouse Service

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.ts
1. 2172
1. Resolved sort order appearance 
No
<details>
</details>
=> fix(2172): resolved leaderboard sort issue

packages/api-catalog-spa/src/pages/APIDescriptionPage/components/ApiOwnersCard/ApiOwnersCard.tsx, packages/component-catalog-spa/src/Configs/component-libraries.js, packages/component-catalog-spa/src/Configs/footer.js, packages/documentation-spa/blog/2020-06-16-announcing-one-platform-mvp.md, packages/documentation-spa/blog/2020-07-17-announcing-one-platform-alpha.md, packages/documentation-spa/blog/2020-08-18-announcing-one-platform-beta.md, packages/documentation-spa/blog/2020-10-30-announcing-one-platform-general-availability.md, packages/documentation-spa/blog/2020-12-08-state-of-one-platform-nov-2020.md, packages/documentation-spa/blog/2021-01-08-state-of-one-platform-dec-2020.md, packages/documentation-spa/blog/2021-02-08-state-of-one-platform-jan-2021.md, packages/documentation-spa/blog/2021-03-10-state-of-one-platform-feb-2021.md, packages/documentation-spa/blog/2021-04-12-state-of-one-platform-mar-2021.md, packages/documentation-spa/blog/2021-05-09-state-of-one-platform-apr-2021.md, packages/documentation-spa/blog/2021-07-13-state-of-one-platform-mayjun-2021.md, packages/documentation-spa/blog/2021-08-09-state-of-one-platform-jul-2021.md, packages/documentation-spa/blog/2021-09-09-state-of-one-platform-aug-2021.md, packages/documentation-spa/docs/apps/internal/lighthouse/lighthouse-spa.md, packages/home-spa/src/_data/footer.json
Updated the email references in the platform to the updated guidelines
No
N/A
=> (fix/2148) - Updated the contact references in the platform

.github/workflows/test-and-build.yml
=> chore(1602) - Add xvfb in CI (test-and-build) to run axe test cases

packages/user-group-spa/src/App.jsx
Updated the references for user group spa for redirect issue with documentation
No
N/A
=> (fix/#2227) - Updated the references for user group spa for redirect issue

packages/doc-spa/docusaurus.config.js, packages/doc-spa/package-lock.json, packages/doc-spa/package.json, packages/doc-spa/src/theme/Layout/index.jsx
1. 2251
1. Fixed broken url in edit and blog url
No
<details>
</details>
=> chore(2251): updated edit doc and blog url in doc-spa

packages/feedback-service/src/feedbacks/helpers.ts
Fixed the Path handling issue in the feedback microservice
No
N/A
=> 2246 - Fixed the Path handling issue in the feedback microservice

packages/lighthouse-spa/package-lock.json, packages/lighthouse-spa/package.json, packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.ts
Fixed the URL validation issues for the lighthouse spa
No
<details>
</details>
=> fix:2215 - Fixed the validation for lighthouse urls

packages/feedback-spa/package-lock.json, packages/feedback-spa/package.json, packages/feedback-spa/src/pages/HomePage/HomePage.tsx
1. 2219
1. Fixed feedback spa modal warning error
No
<details>
</details>
=> fix(2219): feedback-spa: fixed modal warning

packages/feedback-spa/package-lock.json, packages/feedback-spa/package.json, packages/feedback-spa/src/pages/HomePage/HomePage.tsx
1. 2282
1. Fixed overlapping pagination with feedback button
No
<details>
</details>
=> fix(2282): feedback spa fixed overlap of pagination with feedback button

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/layouts/AppLayout/components/Sidebar/Sidebar.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APIReview/APIReview.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/components/ApiTypeSelector/ApiTypeSelector.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/APIDescriptionPage.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/components/ApiEnvironmentSection/ApiEnvironmentSection.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/components/ApiSchemaList/ApiSchemaList.tsx, packages/api-catalog-spa/src/pages/APIDescriptionPage/components/ApiTypeCard/ApiTypeCard.tsx, packages/api-catalog-spa/src/pages/APIListPage/APIListPage.tsx, packages/api-catalog-spa/src/pages/APIListPage/components/ApiDetailsCard/ApiDetailsCard.tsx, packages/api-catalog-spa/src/pages/HomePage/HomePage.tsx
1. 2281
1. Fixed double slash in content images
No
<details>
</details>
=> fix(2281): api catalog spa fixed double slash on content images

.github/workflows/build-analytics-service.yml
1. Added gh workflow to build analytics service image
No
<details>
</details>
=> chore(analytics-service): added gh workflow to build image

packages/doc-spa/package-lock.json, packages/doc-spa/package.json, packages/doc-spa/src/theme/Layout/index.jsx
1. 2252
1. Updated to new feedback component in doc spa
2. Fixed breaking css in doc spa for feedback component
No
<details>
</details>
=> fix(2252): updated feedback component in doc-spa

.github/workflows/auto-deployments.yml, .github/workflows/manual-deployment.yml, packages/home-spa/package-lock.json
-  Split steps into individual phases(steps)
- No
- N/A
=> chore(gh-actions) - Split steps into individual phases(steps)

packages/reverse-proxy-service/src/server.ts
Rate limit errors.
Reduced the rate limits to 100 per 2 minutes, instead of 15 minutes.
No.
N/A
=> rproxy: reduce the rate limit of incoming requests

.github/workflows/auto-deployments.yml, .github/workflows/manual-deployment.yml, packages/home-spa/.env.example
- Fixed command for SPAship 
- No
- N/A
=> fix(gh-actions) - Fixed env for spaship command

.github/workflows/auto-deployments.yml, .github/workflows/manual-deployment.yml, packages/home-spa/.env.example
- Fixing SPAship deployment 
- No
=> fix(gh-actions-spaship) - Testing deploy action

.github/workflows/auto-deployments.yml, .github/workflows/test-and-build.yml
=> fix(multiple-deployments) - Individual builds and test optimisation 

packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/graph/namespace/resolver.ts, packages/api-catalog-service/src/graph/namespace/typedef.graphql, packages/api-catalog-service/src/graph/types.ts, packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/components/EnvironmentFormSection/EnvironmentFormSection.tsx, packages/api-catalog-spa/src/pages/GQLPlaygroundToolboxPage/hooks/useGetAPISchemaFile.tsx, packages/api-catalog-spa/src/pages/RedocToolboxPage/hooks/useGetAPISchemaFile.tsx, packages/api-catalog-spa/src/pages/SwaggerToolboxPage/hooks/useGetAPISchemaFile.tsx
1. 2328
1. Made schema validation on pull optional for tools
No
<details>
</details>
=> API Catalog: Made schema validation on pulling for tools as optional

packages/api-catalog-spa/package-lock.json
Fixed renovate donwgraded v1 package lock file for api catalog
No
<details>
</details>
=> fix(api-catalog-spa): fixed renovate downgraded v1

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/main.tsx
1. 2361
1. Resolved 
No
<details>
</details>
=> fix(2361): fixed direct url access failing

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/_includes/components/hero.njk, packages/home-spa/src/contact-us.njk
There was an accessibility issue of images not having alt text in home-spa particularly on contact us page and home page (Iussue -https://issues.redhat.com/browse/ONEPLAT-2335)
No
Lighthouse before accessibility changes
Lighthouse after accessibility changes
=> Fixed Accessibility in Home SPA

packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/common/components/NewProjectForm/index.tsx, packages/developer-console-spa/src/pages/Home/index.tsx, packages/developer-console-spa/src/pages/Lighthouse/CreateProjectForm.tsx, packages/developer-console-spa/src/pages/Lighthouse/LinkProjectForm.tsx, packages/developer-console-spa/src/pages/Lighthouse/index.tsx
1. 2010
2. 2011
1. Resolved broken link in lighthouse config in dev console
2. Avoid on branch select spa config creation
3. Added loader for form submission
No
<details>
</details>
=> fix(2010,2011): developer console v2 lighthouse modal issues fixed

packages/developer-console-spa/package-lock.json, packages/developer-console-spa/package.json, packages/developer-console-spa/src/common/services/project.ts, packages/developer-console-spa/src/pages/ProjectSettings/General.tsx, packages/developer-console-spa/src/pages/ProjectSettings/index.tsx
Delete project error, and not found error
- Fixed the project service, and renamed the `AppSettings` component to `ProjectSettings`.
No.
N/A
=> fix(dev-console): project service fix

.github/workflows/auto-deployments.yml, .github/workflows/manual-deployment.yml, packages/home-spa/.env.example
-  Added lighthouse job in pipeline
- No
- N/A
=> chore(ci-lighthouse) - Add lighthouse support in CI

.github/workflows/auto-deployments.yml, .github/workflows/manual-deployment.yml
=> fix(lighthouse-ci) - Removed from auto-deployments pipeline

.github/workflows/auto-deployments.yml, .github/workflows/manual-deployment.yml
- fix(lighthouse-only-keep-prod-ci) - Fixed SPA name
- fix(lighthouse-only-keep-prod-ci) - Check added for headful=false
- N/A
- N/A
=> fix(lighthouse-only-keep-prod-ci) - Removed from auto-deployments pipeline

packages/apps-service/Dockerfile, packages/apps-service/package-lock.json, packages/apps-service/package.json, packages/apps-service/src/modules/projects/schema.gql.ts
- Introduced multi stage build for app service docker image, which reduces the final image size by almost 50%.
- Also includes a fix for the `deleteProjectDatabase`, and `updateProjectDatabase` mutations
No.
<details>
</details>
=> feat(apps): Optimized apps service image using multi-stage builds

packages/apps-service/Dockerfile
Docker build fails in the github action with the following error:
Job for reference: https://github.com/1-Platform/one-platform/actions/runs/3747374814/jobs/6363535242
No.
N/A
=> fix(apps): fix for multi file copy in dockerfile

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/_data/microservices.json
Fixed the Homepage Links with new Docs URL
No
N/A
=> 2418 - Fixed the Homepage Links with new Docs URL

packages/home-spa/package-lock.json, packages/home-spa/package.json, packages/home-spa/src/_includes/partials/service.njk
=> fix(home-spa) - Remove graphql fields that are not required in home-spa

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.helpers.ts, packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.tsx, packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.types.ts, packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx, packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/APISchemaForm.tsx
1. 2364
2. 2368
3. 2363
1. Fixed filtering of service account in schema page
2. Changed placeholder of api schema 
No
<details>
</details>
=> fix(2364, 2368, 2363): resolved api-catalog-spa minor bugs and typos

packages/api-gateway-service/config.json, packages/api-gateway-service/package-lock.json, packages/api-gateway-service/package.json
Included API Catalog configuration to the API Gateway
No
N/A
=> 2163 - Included API Catalog configuration to the API Gateway

packages/api-catalog-service/package-lock.json, packages/api-catalog-service/package.json, packages/api-catalog-service/src/graph/namespace/resolver.ts, packages/api-catalog-service/src/graph/namespace/updateSearch.ts
Integrated the API catalog with the search microservice
No
N/A
=> 2163 - Integrated API Catalog with Search

packages/reverse-proxy-service/Dockerfile, packages/reverse-proxy-service/package-lock.json, packages/reverse-proxy-service/src/restricted-spas/index.ts, packages/reverse-proxy-service/src/setup/database.ts
- The Reverse proxy now uses multi-stage builds to reduce the final build size
- Added a redirect for `in-vehicle-development-guide`
No.
N/A
=> feat(rproxy): setup a permanent redirect for an app and updated Dockerfile

packages/reverse-proxy-service/package-lock.json, packages/reverse-proxy-service/package.json, packages/reverse-proxy-service/src/restricted-spas/resolver.ts, packages/reverse-proxy-service/src/server.ts, packages/reverse-proxy-service/src/utils/applicationCache.ts
Replaced accessToken with idToken
as accessToken can be absent but idToken is guaranteed to be present.
No.
N/A
=> fix(rproxy): change token type in forwarded header

packages/api-catalog-spa/package-lock.json, packages/api-catalog-spa/package.json, packages/api-catalog-spa/src/pages/SwaggerToolboxPage/SwaggerToolboxPage.tsx
1. 2448
1. Added deeplinking
No
<details>
</details>
=> feat(2448): Added deeplink to swagger

packages/feedback-service/package-lock.json, packages/feedback-service/package.json, packages/feedback-service/src/e2e/mock.js, packages/feedback-service/src/feedback-config/resolver.ts, packages/feedback-service/src/feedback-config/schema.ts, packages/feedback-service/src/feedback-config/typedef.graphql, packages/feedback-service/src/feedbacks/helpers.ts, packages/feedback-service/src/feedbacks/resolver.ts, packages/feedback-service/src/feedbacks/schema.ts, packages/feedback-service/src/feedbacks/typedef.graphql, packages/feedback-service/src/types.d.ts
- Changed schema
- Yes
- Changes in schema
=> feedback(service) - Update feedback service config map

packages/opc-base/dev/config.es.example.js, packages/opc-base/dev/config.example.js, packages/opc-base/docs/opc-base.md, packages/opc-base/package-lock.json, packages/opc-base/package.json, packages/opc-base/src/gql/types.ts, packages/opc-base/src/opc-base/opc-base.test.ts, packages/opc-base/src/opc-base/types.ts, packages/opc-base/src/opc-provider/opc-provider.ts
1. 2392
1. Added project id in feedback submission
Yes.
opcBase configure must pass project id or type error will be thrown by ts
<details>
</details>
=> feat(2392): updated feedback submission with new project id support

packages/doc-spa/docs/deployment-guidelines/spa-deployment-guideline.md, packages/doc-spa/docs/deployment-guidelines/spa-deployment-guidelines.md, packages/doc-spa/package-lock.json, packages/doc-spa/package.json, packages/doc-spa/sidebars.js
ONEPLAT-2485
Updating SPA deployment guide to point to the SPAship quickstart deployment guide.
No
=> chore(doc-spa): Updating SPA deployment guide

packages/feedback-service/src/feedbacks/resolver.ts, packages/feedback-service/src/feedbacks/typedef.graphql
Added new filters like state, ticketUr, module, description, stackInfo for listFeedbacks query. These filters are required for the backstage feedback-plugin
No
=> chore(feedback-service): added new filters for listFeedbacks query

e2e/integration/homepagetests.js, packages/component-catalog-spa/src/Configs/footer.js, packages/home-spa/src/_data/footer.json
=> fix(home-spa): update One Platform FAQs link

packages/analytics-service/catalog-info.yml, packages/api-catalog-service/catalog-info.yml, packages/api-catalog-spa/catalog-info.yml, packages/api-gateway-service/catalog-info.yml, packages/component-catalog-spa/catalog-info.yml, packages/developer-console-spa/catalog-info.yml, packages/doc-spa/catalog-info.yml, packages/feedback-service/catalog-info.yml, packages/feedback-spa/catalog-info.yml, packages/home-spa/catalog-info.yml, packages/lighthouse-service/catalog-info.yml, packages/lighthouse-spa/catalog-info.yml, packages/opc-base/catalog-info.yml, packages/reverse-proxy-service/catalog-info.yml, packages/search-service/catalog-info.yml, packages/search-spa/catalog-info.yml, packages/user-group-service/catalog-info.yml
These annotations enable feedback plugin integration on backstage
No
=> feat(feedback): Add feedback plugin annotations to catalog entities

packages/reverse-proxy-service/Dockerfile, packages/reverse-proxy-service/package.json, packages/reverse-proxy-service/src/server.ts, packages/reverse-proxy-service/src/types/http.d.ts, packages/reverse-proxy-service/tsconfig.json
- Changes in HTTP header size (set to 10 MB)
- Changes in the Docker file
- Reverted the past changes 
<details>
</details>
=> fix: changes in http header size
